Redazione VE_2024-11-13_ver1.0.0
SWEatUNIPD/docs pull request #27
Opened 2024-11-14 12:34 UTC by Perruzz

close #24 

Domanda, non sono sicuro al 100% sulla tabella delle decisioni

2024-11-14 13:46 UTC, ErPreco commented on rtb/verbali/esterni/VE_2024-11-13_ver1.0.0.typ
> +#infoRiunione(luogo: "Google Meet", data: "13/11/2024", ora: "16:00", durata: "mezz'ora", partecipantiEsterni: ("Fabio Pallaro", "Andrea Dorigo", "Daniele Zorzi"))
Rimuoverei Zorzi che è rimasto per 2 minuti

2024-11-14 14:01 UTC, ErPreco requested changes
Ho diversi accorgimenti ma di carattere principalmente stilistico, il contenuto mi sembra molto buono.

1 Rimuoverei Zorzi dai partecipanti che è rimasto per 2 minuti
2 I termini inglesi andrebbero lasciati al singolare, quindi "best practice"
3 Enfatizzerei sulla scelta di informarci prima sulle tecnologie, specie nella conclusione, per così iniziare la AdR
4 Al paragrafo 3.2 al posto della domanda (essendo il titolo di un paragrafo) opterei per "Autonomia degli strumenti e materiale condiviso"
5 Toglierei la virgola dopo "ad esempio" nello stesso paragrafo
6 Toglierei la virgola dopo Git essendoci la "e" dopo (stessa riga)
7 Al punto 3.4 metterei lo spazio tra "settimanali" e "SAL"
8 Aggiungere "sprint saranno tendenzialmente bisettimanali" perché loro stessi hanno detto che potrebbero accorciarsi
9 Eviterei nella stessa riga di parlare di "retrospettiva" per gli incontri intermedi perché è una attività da fare a fine sprint, piuttosto direi "aggiornamenti"
10 Aggiungere la dicitura per la firma in calce
11 La ORG a nome mio andrebbe nel verbale interno, le NdP sono assegnate a Klaudio non a Riccardo, infine attento ai codici che devono indicare l'ID delle issue (quindi ad esempio D0024 e non D0017)
12 Cambierei il titolo in Kick Off Sync Lab S.r.l. così da essere "parlante"

2024-11-14 14:06 UTC, klamerja commented
Faccio una piccola osservazione... le decisioni a questo punto non sarebbe meglio metterle nel verbale interno sempre dello stesso giorno? @ErPreco @Perruzz

2024-11-14 14:21 UTC, Perruzz commented
> Ho diversi accorgimenti ma di carattere principalmente stilistico, il contenuto mi sembra molto buono.
> 
> 1 Rimuoverei Zorzi dai partecipanti che è rimasto per 2 minuti 2 I termini inglesi andrebbero lasciati al singolare, quindi "best practice" 3 Enfatizzerei sulla scelta di informarci prima sulle tecnologie, specie nella conclusione, per così iniziare la AdR 4 Al paragrafo 3.2 al posto della domanda (essendo il titolo di un paragrafo) opterei per "Autonomia degli strumenti e materiale condiviso" 5 Toglierei la virgola dopo "ad esempio" nello stesso paragrafo 6 Toglierei la virgola dopo Git essendoci la "e" dopo (stessa riga) 7 Al punto 3.4 metterei lo spazio tra "settimanali" e "SAL" 8 Aggiungere "sprint saranno tendenzialmente bisettimanali" perché loro stessi hanno detto che potrebbero accorciarsi 9 Eviterei nella stessa riga di parlare di "retrospettiva" per gli incontri intermedi perché è una attività da fare a fine sprint, piuttosto direi "aggiornamenti" 10 Aggiungere la dicitura per la firma in calce 11 La ORG a nome mio andrebbe nel verbale interno, le NdP sono assegnate a Klaudio non a Riccardo, infine attento ai codici che devono indicare l'ID delle issue (quindi ad esempio D0024 e non D0017) 12 Cambierei il titolo in Kick Off Sync Lab S.r.l. così da essere "parlante"

nel punto 11 intendi la ORG riguardante la descrizione delle issue giusto?

2024-11-14 15:55 UTC, ErPreco commented
@klamerja riguardo al kick off abbiamo preso delle decisioni, ad esempio la riunione il 20, quindi io le lascerei perché pertinenti
@Perruzz sì, non è stato oggetto di discussione con Sync Lab

2024-11-14 15:57 UTC, ErPreco approved these changes

2024-11-14 15:58 UTC, klamerja commented
@ErPreco chiaro, quelle le lascerei pure io. Quello a cui mi riferivo erano quelle che erano state definite successivamente (rif. foto)
<img width="701" alt="Screenshot 2024-11-14 at 16 57 47" src="https://github.com/user-attachments/assets/4d7a5d3f-254e-4ba3-a622-08c7d58e3524">

2024-11-14 16:01 UTC, ErPreco commented
> @ErPreco chiaro, quelle le lascerei pure io. Quello a cui mi riferivo erano quelle che erano state definite successivamente (rif. foto) <img alt="Screenshot 2024-11-14 at 16 57 47" width="701" src="https://private-user-images.githubusercontent.com/43652136/386268080-4d7a5d3f-254e-4ba3-a622-08c7d58e3524.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDAxODMsIm5iZiI6MTczMTU5OTg4MywicGF0aCI6Ii80MzY1MjEzNi8zODYyNjgwODAtNGQ3YTVkM2YtMjU0ZS00YmEzLWE2MjItMDhjN2Q1OGUzNTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDE1NTgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNzNhZDkwYmE3YTg4YTk2MjY1MGFiOTU2MTEzMDA4YWMyOWY0NzhjYTIwYjNhZTBmN2JjNDA3Zjg1Njg2YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.628nf-tDu2C184Iu4rhmW5ZNiHDkLM_FwO6uiqCI_tU">

Sì effettivamente hai ragione, @Perruzz a questo punto lascerei la decisione del VE e la ORG di aver scelto la data della riunione, le altre andrebbero nel VI

2024-11-14 16:09 UTC, Perruzz commented
> > @ErPreco chiaro, quelle le lascerei pure io. Quello a cui mi riferivo erano quelle che erano state definite successivamente (rif. foto) <img alt="Screenshot 2024-11-14 at 16 57 47" width="701" src="https://private-user-images.githubusercontent.com/43652136/386268080-4d7a5d3f-254e-4ba3-a622-08c7d58e3524.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDAxODMsIm5iZiI6MTczMTU5OTg4MywicGF0aCI6Ii80MzY1MjEzNi8zODYyNjgwODAtNGQ3YTVkM2YtMjU0ZS00YmEzLWE2MjItMDhjN2Q1OGUzNTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDE1NTgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNzNhZDkwYmE3YTg4YTk2MjY1MGFiOTU2MTEzMDA4YWMyOWY0NzhjYTIwYjNhZTBmN2JjNDA3Zjg1Njg2YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.628nf-tDu2C184Iu4rhmW5ZNiHDkLM_FwO6uiqCI_tU">
> 
> Sì effettivamente hai ragione, @Perruzz a questo punto lascerei la decisione del VE e la ORG di aver scelto la data della riunione, le altre andrebbero nel VI

perfetto, quindi nella tabella decisioni del verbale interno non serve che metta il verbale esterno, corretto?

2024-11-14 16:15 UTC, DavidePicc commented
Il documento mi sembra ben fatto. 
Concordo in pieno con l'osservazione di @klamerja ed anzi, dico che secondo me la riga della tabella delle decisioni inerente alla stesura del verbale esterno, non dovrebbe essere messa lì.
Essendo un verbale **esterno** non penso che agli esterni interessi sapere che abbiamo deciso di redigere un verbale, che poi è proprio quello che stanno leggendo, quindi mi sembra anche inutile. Secondo me ha senso spostare anche quello sul verbale interno. Fatemi sapere cosa ne pensate anche voi. 
@Perruzz @ErPreco @klamerja

2024-11-14 16:26 UTC, klamerja commented
> > > @ErPreco chiaro, quelle le lascerei pure io. Quello a cui mi riferivo erano quelle che erano state definite successivamente (rif. foto) <img alt="Screenshot 2024-11-14 at 16 57 47" width="701" src="https://private-user-images.githubusercontent.com/43652136/386268080-4d7a5d3f-254e-4ba3-a622-08c7d58e3524.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDAxODMsIm5iZiI6MTczMTU5OTg4MywicGF0aCI6Ii80MzY1MjEzNi8zODYyNjgwODAtNGQ3YTVkM2YtMjU0ZS00YmEzLWE2MjItMDhjN2Q1OGUzNTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDE1NTgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNzNhZDkwYmE3YTg4YTk2MjY1MGFiOTU2MTEzMDA4YWMyOWY0NzhjYTIwYjNhZTBmN2JjNDA3Zjg1Njg2YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.628nf-tDu2C184Iu4rhmW5ZNiHDkLM_FwO6uiqCI_tU">
> > 
> > 
> > Sì effettivamente hai ragione, @Perruzz a questo punto lascerei la decisione del VE e la ORG di aver scelto la data della riunione, le altre andrebbero nel VI
> 
> perfetto, quindi nella tabella decisioni del verbale interno non serve che metta il verbale esterno, corretto?

Chiedo conferma a @ErPreco, ma metterei le varie redazioni dei documenti (VI e VE di ieri + Norme di progetto) come decisioni del verbale interno.
L'unica decisione che è venuta fuori dal kick-off è quella del prossimo colloquio

2024-11-15 11:46 UTC, DavidePicc approved these changes
Ora la tabella, ed il documento in generale, mi sembrano corretti

2024-11-15 13:31 UTC, DavidePicc commented
Ora si può chiudere questa PR

2024-11-15 13:38 UTC, klamerja commented
Come per il VI, @Perruzz ha messo se stesso come responsabile. Ho sentito @ErPreco  su telegram e al momento, siccome i ruoli non son ben definiti, abbiamo pensato di poter lasciare così, cercando intanto di capire come organizzare i ruoli. Quindi Andrea può procedere con lo squash dei commit se vuole.

2024-11-15 14:14 UTC, merged