redazione VI_2024-11-13_ver1.0.0
SWEatUNIPD/docs pull request #28
Opened 2024-11-14 13:49 UTC by Perruzz

close #26

2024-11-14 14:26 UTC, MarinDavide requested changes
**Contenuto:**
- La data nella tabella modifiche è sbagliata
- Nel paragrafo 4.3 si parla degli incontri con l'azienda? se si sarebbe da specificare che si alternano di settimana in settimana tra aggiornamenti rapidi e incontri di fine sprint.

**Sintassi e ortografia:**
- Alla fine del paragrafo 4.2 non scriverei "successiva", ma ad esempio "prossima".
- Nella prima riga del 5.3 ti ha preso 2 tipi di apici diversi, modifica il primo perché di solito sono del tipo << ... >>

2024-11-14 15:11 UTC, MarinDavide approved these changes

2024-11-15 08:56 UTC, MarinDavide commented
@MilanRiccardo03 pronta per il merge

2024-11-15 10:32 UTC, MilanRiccardo03 commented
> @MilanRiccardo03 pronta per il merge

Il redattore e quindi responsabile è @Perruzz, dovrebbe mergiare lui o mi sono perso qualcosa?

2024-11-15 11:01 UTC, Perruzz commented
> > @MilanRiccardo03 pronta per il merge
> 
> Il redattore e quindi responsabile è @Perruzz, dovrebbe mergiare lui o mi sono perso qualcosa?

oke, devo farlo con squash o rebase che non ricordo? perdonatemi🫠

2024-11-15 11:06 UTC, MilanRiccardo03 commented
> > > @MilanRiccardo03 pronta per il merge
> > 
> > Il redattore e quindi responsabile è @Perruzz, dovrebbe mergiare lui o mi sono perso qualcosa?
> 
> oke, devo farlo con squash o rebase che non ricordo? perdonatemi🫠
> 
> 

A tua scelta cambia solo che uno butta tutto su main creando un nuovo commit, l'altro mergia

2024-11-15 11:09 UTC, merged