redazione VE_2024-11-20_ver1.0.0
SWEatUNIPD/docs pull request #40
Opened 2024-11-20 19:56 UTC by Perruzz

close #34

2024-11-22 09:15 UTC, DavidePicc requested changes
# Punto 1
**Titolo**: Vedi cosa sarà deciso nel gruppo telegram

**Riassunto**: "chiariti i dubbi sul PoC" sembra che abbiamo già deciso definitivamente cosa fare per il PoC, metterei qualcosa di meno "definitivo" tipo "discussione riguardo al PoC"

# Punto 2
Più che "Le tecnologie discusse durante la riunione sono" metterei anche che le abbiamo ormai scelte, sembra che ne abbiamo solo discusso, e non che abbiamo deciso di usarle

# Punto 3
## 3.1 
"Nel Proof of Concept (PoC), è sufficiente ricevere la notifica" dai un po' (basta un minimo) di contesto, essendo un verbale esterno può essere che non si ricordino (più che altro Tullio) a cosa sia legata la notifica.

2024-11-22 14:32 UTC, DavidePicc approved these changes
Ora mi sembra vada bene 👍🏻

2024-11-22 14:37 UTC, DavidePicc commented
Ora il responsabile dovrebbe squashare @Perruzz

2024-11-24 10:21 UTC, klamerja commented
@Perruzz richiede nuova review per quanto riguarda riferimenti al glossario @DavidePicc

2024-11-25 14:49 UTC, DavidePicc approved these changes
Sembra corretto

2024-11-25 14:53 UTC, DavidePicc commented
Ho cercato di risolvere i conflitti (sui file di build) ho tenuto le versioni del main, essendo più aggiornate

2024-11-25 14:54 UTC, klamerja commented
Che senso aveva mergiare il main se deve andare in main? 😐

2024-11-26 11:24 UTC, DavidePicc commented
> Che senso aveva mergiare il main se deve andare in main? 😐

Perchè pensavo che facendo così avrei risolto i conflitti. 
Quello che intendevo dire è che c'erano dei file che creavano conflitti con il main e mi veniva chiesto di risolverli, essendo le versioni del main più aggiornate ho tenuto quelle.  Pensavo quindi che facendo così, ora, sarebbe bastato mergiare automaticamente

2024-11-26 11:25 UTC, DavidePicc commented
Tra l'altro se questo branch è concluso basta mergiare. Deve farlo il responsabile ?

2024-11-26 11:43 UTC, Perruzz commented
> Tra l'altro se questo branch è concluso basta mergiare. Deve farlo il responsabile ?
> 


Allora sto aspettando a mergiare perché sul verbale esterno ci sono dei termini che vanno aggiunti al glossario solo che non so se pushare o meno le modifiche al glossario con i termini nuovi, in quanto nella tua pr e in quella di prec state facendo anche voi modifiche al glossario quindi quando si andrà a chiudere le pr e a mergiare i rami nel main non ho idea di cosa succeda. Pensavo di chiedere e discuterne con voi dopo un chiamata

2024-11-26 16:49 UTC, merged