Aggiunta prima versione dei processi di supporto
SWEatUNIPD/docs pull request #41
Opened 2024-11-20 20:44 UTC by ErPreco

Chiedo revisione anche di @klamerja principalmente per la parte relativa alla Action e ai comandi da utilizzare.
Da attendere la parte dei processi primari di Picello.

2024-11-20 21:21 UTC, klamerja commented
# 3.1.1.2
- puoi rimuovere tranquillamente il git fetch in quanto viene fatto dal pull
- se vuoi dare un font più monospace, puoi circondare i comandi dal \` (e.g. `ciao mondo` come puoi vedere; funziona come col MD)
- evidenzierei di più in qualche modo *pull request* che sta tra le virgolette
- Step 6, non devi per forza git pullare tutto... se stai lavorando te sul branch poco te ne frega, allineare l'origin col local serve più per sincronizzare il lavoro, e viene fatto diciamo "a sentimento" (buona norma sarebbe ogni qual volta inizi a lavorare)... lo stesso poi vale per il checkout: se stai lavorando li, non ha alcun senso rifare il checkout... rivedrei un attimo questa parte
# 3.1.3.1
- il logo sta dentro `assets/img` (anche il percorso se vuoi puoi farlo "monospaced", cioè il solito font programmatore circondando la frase con gli apici che avevo scritto prima)
- Piccolezza, ma su Uso metterei esterno col maiuscolo

# 3.2
Il link che va a capo:
![image](https://github.com/user-attachments/assets/bd99318f-282c-4768-bf87-572803ead877)

# 3.2.1.1
Non capisco perché il tree-list si veda in quel modo tutto sfasato (sul mio pc neanche fa le stecche orizzontali che fa vedere nella doc, bisognerebbe capire il perché... anche qui cambierei il font con un monospace, ma al massimo apporterò io delle modifiche di stile dopo quindi no problem

Per il resto mi sembrava ben fatto, ci sta

2024-11-21 09:24 UTC, MarinDavide requested changes
Concordo con le correzioni dette da @klamerja, inoltre:

## Tabella Versioni
La data della versione 1.0.0 è 10/11 ma il documento è del 14/11

## 3.1.6
Norme di Progetto e Glossario sono ora in rtb (come hai correttamente già cambiato nel 3.2.1.1)

## 3.1.10 
"hosting" dovrebbe avere l'apice glossario? lo chiedo perché non viene visualizzato correttamente e all'interno del Glossario non è presente quel termine.

## 3.2.5
- Errore di battitura: è scritto "persa visione" invece di "presa visione"
- Non sono il massimo esperto ma dovrebbe essere "git add . --force", da rimuovere la richiesta di aiuto.

Domanda personale, se approvato il prossimo push, faccio comunque un "request changes" per i prossimi paragrafi taggando Picello?

2024-11-21 20:19 UTC, ErPreco commented
Riporto le seguenti modifiche, il resto che non cito è stato eseguito come richiesto:
1 per i comandi potrei aggiungere un tab? dovrei guardare come fare ma così allineati a sinistra non mi fanno impazzire
2 paragrafo 3.2 non mi convince il link a capo, a pensarci ora potrei invertire la frase dicendo "Al sito [link] si possono consultare..."
3 anche io vedo le stecche verticali dell'albero sfalsate, volevo provare ma si può cambiare col solito elenco puntato
4  una volta confermata la mia versione aggiungo "hosting" al glossario

Nota per tutti @klamerja @MarinDavide @DavidePicc @MilanRiccardo03 @davim02 @Perruzz:
visto anche il consiglio di Merja ho pensato di aggiungere il monospace per tutti i nomi di file, cartelle e estensioni quindi attenti  ai documenti (paragrafo 3.1.7)

P.S la build è fallita di nuovo penso perché nella prima commit il file aveva un nome diverso, non mi sembra urgente come problema comunque

2024-11-21 20:20 UTC, ErPreco commented
> Domanda personale, se approvato il prossimo push, faccio comunque un "request changes" per i prossimi paragrafi taggando Picello?

Sì sembra una buona soluzione.

2024-11-21 20:38 UTC, klamerja commented
> P.S la build è fallita di nuovo penso perché nella prima commit il file aveva un nome diverso, non mi sembra urgente come problema comunque

non so che abbia onestamente... prende il vecchio nome. Vedo di risolvere

2024-11-21 20:39 UTC, klamerja commented
> > Domanda personale, se approvato il prossimo push, faccio comunque un "request changes" per i prossimi paragrafi taggando Picello?
> 
> Sì sembra una buona soluzione.

Va bene, in realtà basterebbe solo che @MarinDavide non dia l'approvazione in quanto la PR è composta anche da @DavidePicc

2024-11-21 20:56 UTC, ErPreco commented
Mi sono accorto ora di alcune correzioni da apportare, appena sarà caricato il nuovo template pusherò la versione definitiva.

2024-11-21 20:58 UTC, klamerja commented
> Mi sono accorto ora di alcune correzioni da apportare (specie riguardo dove applicare il monospace), appena sarà caricato il nuovo template pusherò la versione definitiva.

Mea culpa, sto iniziando adesso. Ricordami:
- link
- elenchi puntati indentati

Solo questo era, giusto?

2024-11-23 11:14 UTC, DavidePicc commented
Il **capitolo 2.1 Fornitura** è stato scritto guardando molto altri gruppi ma comunque rielaborandolo sulla nostra esperienza.
Il **capitolo 2.2 Sviluppo**, invece, sembra una lezione di Tullio, ma perché dobbiamo ancora iniziare questa parte e quindi non sapevo bene cosa scrivere riguardo alla nostra esperienza. Inoltre alcuni gruppi la lasciano come noi, altri approfondiscono molto alcuni punti (tipo gli UML e le regole che hanno deciso di adottare per farli)

**Dubbi:**
- Data sulla tabella delle modifiche
- Termini glossario
- In **2.1.2 Documentazione** fornita qualche altro gruppo mette anche la valutazione dei capitolati, altri gruppi no. Io la penso come quest'ultimi in quanto, tutti i gruppi, hanno comunque scritto che questi sono i documenti consegnati ai professori ed all'azienda, e quest'ultimo mi sembrava fosse interno e soprattutto non utile né per il prof, né per l'azienda.

2024-11-23 12:32 UTC, klamerja commented
Ho controllato i commit con i vari merge: @MarinDavide provvedo a risolvere il problema dei confliti col main branch.

Per quanto riguarda @DavidePicc:
- Per il glossario va bene la versione, ma il verificatore è Davide Marin
- Per la versione del documento oggetto della issue, quindi le norme, tu e @ErPreco state svolgendo la issue assieme, quindi lavorate sulla stessa versione che sarà oggetto di revisione sempre da parte di Marin e che poi avrà una unica "build" come risultato (allego come andrebbe corretta, ovviamente potete metterla in maniera migliore, ma bene o male deve avere questa struttura e non creare una terza versione)

<img width="565" alt="Screenshot 2024-11-23 at 13 32 04" src="https://github.com/user-attachments/assets/1e8a5836-6923-4846-8032-5fa1f64aa419">

2024-11-23 12:35 UTC, klamerja commented
Inoltre @MarinDavide, oltre alle norme controlla il termine `Deep dive` inserito in glossario

2024-11-23 13:03 UTC, ErPreco commented
> Ho controllato i commit con i vari merge: @MarinDavide provvedo a risolvere il problema dei confliti col main branch.
> 
> Per quanto riguarda @DavidePicc:
> 
> * Per il glossario va bene la versione, ma il verificatore è Davide Marin
> * Per la versione del documento oggetto della issue, quindi le norme, tu e @ErPreco state svolgendo la issue assieme, quindi lavorate sulla stessa versione che sarà oggetto di revisione sempre da parte di Marin e che poi avrà una unica "build" come risultato (allego come andrebbe corretta, ovviamente potete metterla in maniera migliore, ma bene o male deve avere questa struttura e non creare una terza versione)
> 
> <img alt="Screenshot 2024-11-23 at 13 32 04" width="565" src="https://private-user-images.githubusercontent.com/43652136/389196835-1e8a5836-6923-4846-8032-5fa1f64aa419.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNjY2MzIsIm5iZiI6MTczMjM2NjMzMiwicGF0aCI6Ii80MzY1MjEzNi8zODkxOTY4MzUtMWU4YTU4MzYtNjkyMy00ODQ2LTgwMzItNWZhMWY2NGFhNDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDEyNTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MWNkZGRiMjRlMDc1MmMzZTcxMTkyYWIxNmI3MWM4YzdlNDNjMGFjYTNlODY0MDc1OWI0ZmU1YTU2MTRiMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B8ZW682mWUhLtbvLbfCFN6y2EU0_fdnUDppPqljB-64">

Per come abbiamo creato la issue ha ragione @klamerja, tuttavia a pensarci ora credo sarebbe stato più consono crearne due distinte e avere quindi 2 versioni. Io attendo che @DavidePicc risolva il conflitto prima di scaricare le sue modifiche e caricare le mie per evitare ulteriori problemi.

2024-11-23 13:05 UTC, klamerja commented
Mi sembrava avesse già pushato

2024-11-23 15:56 UTC, DavidePicc commented
Però dobbiamo capire una cosa secondo me, alla sezione 2.1.2 Documentazione fornita si elencano e descrivono i documenti che costituiscono la documentazione che consegneremo all'azienda e ai prof, ma il glossario e le stesse norme di progetto, riportano nella prima pagina "Uso interno", anche se questi file non sono nè nella cartella dei file interni, nè in quella dei file esterni.

2024-11-25 15:26 UTC, klamerja commented
@MarinDavide ho messo a posto il glossario di @DavidePicc in quanto mancava il termine `deep dive`. Mi sembra manchi da finire roba nelle norme (a giudicare dai commenti). Tolgo il disturbo

2024-11-25 15:39 UTC, DavidePicc commented
@klamerja in realtà i commenti sono su delle parti precise di file che devono ancora essere scritti (analisi dei requisiti, piano di progetto, piano di qualifica).
Penso sia più opportuno scrivere quelle parti quando saranno pronti ufficialmente i relativi documenti, per evitare di scrivere e poi dover ricambiare potenzialmente tutto.

2024-11-25 17:36 UTC, MarinDavide requested changes
In generale il contenuto va bene, ho trovato un paio di correzioni da fare, ma non di contenuto.
Mancavano tutti i corsivi per i termini in inglese, spero di averli visti tutti sono scritti qui sotto assieme al resto:

## 2.1.1
- secondo me troppe virgole, scriverei tipo "si è resa raggiungibile tramite mail per le comunicazioni ufficiali e tramite..."
- "Google meet" da mettere la maiuscola anche su "Meet"
- ultima riga, "repository" da mettere in corsivo

## 2.1.2.3
- "software" da mettere in corsivo

## 2.1.2.4
- "stakeholder" da mettere in corsivo
- "team" da mettere in corsivo

## 2.1.3.2
 "App" da mettere in corsivo o cambiare con "Applicazione"

## 2.1.3.3
- Cambierei "Applicazione online" con "Applicazione web"

## 2.1.3.4
- "software" da mettere in corsivo
- "repository" da mettere in corsivo
- "markup" da mettere in corsivo

## 2.2 
- "software" da mettere in corsivo

## 2.2.3
- "software" da mettere in corsivo
- "hardware" da mettere in corsivo

## 2.2.4
- "software" da mettere in corsivo
- "database" da mettere in corsivo
- "baseline" da mettere in corsivo

## 2.2.5
- "software" da mettere in corsivo, due volte
- "test" da mettere in corsivo

## 2.2.6
- "software" da mettere in corsivo
- "database" da mettere in corsivo
- "testing" da mettere in corsivo

## 2.2.7
- "software" da mettere in corsivo, due volte
- "test" da mettere in corsivo, tre volte

## 2.2.8
- "software" da mettere in corsivo, due volte
- "test" da mettere in corsivo, due volte

## 2.2.9
- "software" da mettere in corsivo, due volte
- "test" da mettere in corsivo, due volte

## 2.2.10
- "software" da mettere in corsivo
- "hardware" da mettere in corsivo
- "test" da mettere in corsivo, due volte

## 2.2.12
- "software" da mettere in corsivo, due volte

## 2.2.13
- "test" da mettere in corsivo
- "software" da mettere in corsivo, due volte

Chiedo inoltre a @klamerja e @ErPreco due cose:
- Cosa si è deciso alla fine per la questione monospace nei nomi senza estensione dei documenti, in caso è da aggiungere anche quello.
- Per la questione commenti, sarebbero gli equivalenti TODO messi invece nel documento da @ErPreco, è da chiarire magari nella prossima riunione un modo più standard di definirli (anche come consigliava @klamerja sull'altra pr)

2024-11-27 09:30 UTC, klamerja commented
> In generale il contenuto va bene, ho trovato un paio di correzioni da fare, ma non di contenuto. Mancavano tutti i corsivi per i termini in inglese, spero di averli visti tutti sono scritti qui sotto assieme al resto:
> ## 2.1.1
> 
>     * secondo me troppe virgole, scriverei tipo "si è resa raggiungibile tramite mail per le comunicazioni ufficiali e tramite..."
> 
>     * "Google meet" da mettere la maiuscola anche su "Meet"
> 
>     * ultima riga, "repository" da mettere in corsivo
> 
> 
> ## 2.1.2.3
> 
>     * "software" da mettere in corsivo
> 
> 
> ## 2.1.2.4
> 
>     * "stakeholder" da mettere in corsivo
> 
>     * "team" da mettere in corsivo
> 
> 
> ## 2.1.3.2
> 
> "App" da mettere in corsivo o cambiare con "Applicazione"
> ## 2.1.3.3
> 
>     * Cambierei "Applicazione online" con "Applicazione web"
> 
> 
> ## 2.1.3.4
> 
>     * "software" da mettere in corsivo
> 
>     * "repository" da mettere in corsivo
> 
>     * "markup" da mettere in corsivo
> 
> 
> ## 2.2
> 
>     * "software" da mettere in corsivo
> 
> 
> ## 2.2.3
> 
>     * "software" da mettere in corsivo
> 
>     * "hardware" da mettere in corsivo
> 
> 
> ## 2.2.4
> 
>     * "software" da mettere in corsivo
> 
>     * "database" da mettere in corsivo
> 
>     * "baseline" da mettere in corsivo
> 
> 
> ## 2.2.5
> 
>     * "software" da mettere in corsivo, due volte
> 
>     * "test" da mettere in corsivo
> 
> 
> ## 2.2.6
> 
>     * "software" da mettere in corsivo
> 
>     * "database" da mettere in corsivo
> 
>     * "testing" da mettere in corsivo
> 
> 
> ## 2.2.7
> 
>     * "software" da mettere in corsivo, due volte
> 
>     * "test" da mettere in corsivo, tre volte
> 
> 
> ## 2.2.8
> 
>     * "software" da mettere in corsivo, due volte
> 
>     * "test" da mettere in corsivo, due volte
> 
> 
> ## 2.2.9
> 
>     * "software" da mettere in corsivo, due volte
> 
>     * "test" da mettere in corsivo, due volte
> 
> 
> ## 2.2.10
> 
>     * "software" da mettere in corsivo
> 
>     * "hardware" da mettere in corsivo
> 
>     * "test" da mettere in corsivo, due volte
> 
> 
> ## 2.2.12
> 
>     * "software" da mettere in corsivo, due volte
> 
> 
> ## 2.2.13
> 
>     * "test" da mettere in corsivo
> 
>     * "software" da mettere in corsivo, due volte
> 
> 
> Chiedo inoltre a @klamerja e @ErPreco due cose:
> 
>     * Cosa si è deciso alla fine per la questione monospace nei nomi senza estensione dei documenti, in caso è da aggiungere anche quello.
> 
>     * Per la questione commenti, sarebbero gli equivalenti TODO messi invece nel documento da @ErPreco, è da chiarire magari nella prossima riunione un modo più standard di definirli (anche come consigliava @klamerja sull'altra pr)

il TODO se ne può parlare oggi. Per i documenti senza estensione/versione, ma riportati proprio per il fatto di essere un documento fisico, bisognerebbe approfondire con @ErPreco

2024-11-27 09:36 UTC, MarinDavide commented
Scusate, chiedo ai principali operatori su questo file, @DavidePicc @klamerja @ErPreco, è giusto che ora nella 3.0 non ci sia la parte di processi di supporto e verrà corretto il conflict dopo quindi?

chiedo perché fa strano avere la versione di Precoma nella tabella, ma non la parte scritta

2024-11-27 09:44 UTC, DavidePicc commented
Io l'ho pensata così. Questo è mio, quello di Prec è già sul main, quando anche questo andrà nel main si uniranno.

> chiedo perché fa strano avere la versione di Precoma nella tabella, ma non la parte scritta

Forse questo l'ho effettivamente sbagliato, e sarebbe dovuto essere messo nel momento del merge, ma mi dava un conflitto strano su quella parte, allora l'avevo messo già

2024-11-27 09:54 UTC, MarinDavide requested changes
Vedo che mancano tutti i "test" da mettere in corsivo, non so se è perché non li hai visti o non la reputi come parola prettamente inglese, però sulla parte di processi di supporto sono stati messi, quindi volevo mantenere coerenza.

## 2.1.2.3
- Nella seconda riga, manca "software" da mettere in corsivo

## Riferimenti a Glossario
- 2.2.4 Database 

Per il resto tutto ok

2024-11-27 09:55 UTC, klamerja commented
Per quanto riguarda i nomi dei file, anche se senza estensione e versione, onestamente se devo far riferimento alle Norme di progetto, io le metterei (cosa che ho fatto sul PdP). 
Per quanto riguarda @DavidePicc: hai già mergiato il main?

2024-11-27 10:00 UTC, DavidePicc commented
> Nella seconda riga, manca "software" da mettere in corsivo

Questo me l'ero proprio perso.

Per test invece non so, non mi cambia niente metterli in corsivo o no, solo che è una parola che ormai usiamo anche noi in italiano

2024-11-27 10:02 UTC, MarinDavide commented
@DavidePicc scusa ho aggiunto sulla review un riferimento al glossario mancante, per la questione di test sono in parte d'accorso, però appunto nella 2.0 sono stati messi

2024-11-27 10:04 UTC, DavidePicc commented
Alla fine ho corretto anche test

2024-11-27 10:09 UTC, MarinDavide approved these changes

2024-11-27 10:11 UTC, merged