Processi di supporto NdP
SWEatUNIPD/docs pull request #46
Opened 2024-11-24 14:54 UTC by ErPreco

Ho fatto abbastanza correzioni, specie vanno controllati i termini in inglese perché ho notato essercene 5 ad ogni farse ahahah.

Aggiunti "hosting" e "backlog" al glossario.

2024-11-24 16:20 UTC, klamerja commented
Riporto a elenco per semplicità
# 3.1.1.1
- _issue_(corrispondenti alle... : metterei lo spazio dopo issue
- 
# 3.1.1.2 
- _pull request_ perché *è* già esistente: toglierei la *è*
- il verificatore e sostituendo il responsabile col compagno che in quel momento sta ricoprendovi il ruolo -> la lasciam per domani da chiedere al prof questa vero?
- Se si individuano dei nuovi termini da aggiungere al Glossario si inseriscono mantenendo i procedi
menti descritti dal documento corrente. Il verificatore deve quindi controllare anche che siano stati
inseriti nel modo corretto all’interno del Glossario: è stato aggiunto `glossario.json`, quindi non è corretta questa affermazione. Poi onestamente manterrei anche i nomi dei file in monospace... vedo che ciò è stato modificato rispetto alla prima redazione delle norme che avevo fatto (era per distinguere bene il nome del documento)

# 3.1.3.4 
più che compagni metterei componenti e membri se vogliamo mantenere un contesto "lavorativo" (poi in realtà andrebbe bene anche così, per carità)

# 3.1.5
Enfatizzerei il fatto di utilizzare il _semantic vesioning_, però a discrezione tua, non è necessario

# 3.1.8
- Ed ecco qui dove viene a galla il fatto del nome del file in monospace (almeno che tu non intendessi comprensivo di versione ed estensione, però son dell'idea che quando ci riferiamo ad un documento, essendo d'altronde un file, vada messo in monospace)
- Altra roba magari (me ne rendo conto sulla funzione formatLink, sembra che debbia scrivere label o url (magari impressione mia eh, assolutamente)

# 3.1.10
Sotto il titolo nella prima pagine: typo

# 3.1.11
il consiglio di Tinymist lo metterei tra parentesi... è una nota in più

# 3.2
Secondo me potremmo mettere anche il sito della directory listing per vedere i risultati di build o avere una visione in formato "directory listing". Poi anche qui, son scelte

# 3.2.1
Qua potremmo aggiungere un way of working buono, ovvero usare la notazione TODO: oppure FIXME:, molto utile se accompagnata da estensioni come ToDo tree o TODO Highlighting (ho notato che pure @MilanRiccardo03 lo utilizza... torna veramente utile quando si lavora con abbastanza file). In questo modo non inseriamo i todo a vista nel documento

# 3.2.1.1
- Occhio, non è il .gitignore il file di build... le action sono strutturate in due file che (a ricordo) sono `build.yaml` per la compilazione dei documenti e per il push degli stessi nel sito, per la generazione della mappa per il sito principale e per il test dei riferimenti al glossario ed il file `pull_request.yml` che è la action che genera gli artefatti per i documenti modificati all'interno delle pull request per facilitare il lavoro dei verificatori... questi file sono contenuti in `.github/workflows/.`. Il `.gitignore` serve a non pushare una determinata tipologia di file nella repo (come i pdf, i DS_STORE di MacOS malefico e altri). Di fatto (quando sto scrivendo questa cosa) non c'è scritto nulla al riguardo della generazione dei PDF dei verbali esterni: essi non sono generati dalla build automation... inoltre i pdf sono stati gitignorati, quindi quando si aggiunge un VE firmato, serve aggiungerlo con il comando `git add pathToFile --force`
- Mancano `test.js`, ovvero lo script che si occupa di verificare che i file contengano riferimenti al glossario nel caso contengano parole presenti in glossario, e `glossario.json`, ovvero una struttura dati (nello specifico: JavaScript Object Notation) contenente i termini del glossario (abbiamo una serie di oggetti che hanno come chiave la lettera dell'alfabeto... ogni oggetto ha una serie di coppie key: value, dove key indica il termine, value la definizione del termine stesso) che serve per far funzionare lo script di test e che contribuisce alla build del documento `glossario_verX.Y.Z.typ`.

# 3.2.1.2
- .gitingore non è usato, serve solo a gitignorare una determinata categoria di file specificata al suo interno
- lib al momento contiene funzioni di utility di una libreria esterna
- `.tsx`se vuoi specificare sono i componenti che hanno sintassi simil markup di html, ma in realtà non è necessario
- sarebbe da chiedere se il sito è oggetto di valutazione per come è fatto (non vorrei ci venisse a fare parole per il fatto di aver usato react)
- il sito ha anche lui una build automation per la compilazione del sito statico (non so quanto tu voglia specificarlo, per me possiamo anche ometterlo)

# 3.2.4
Per aggiungere un po' di zucchero, potremmo già creare un template di ISSUE

# 3.2.6
Come non detto, era scritto dopo. Manca però la parte del glossario ancora.

# 3.3
Solita storia del TODO

# 3.4, ma anche altre parti
Forse quando parliamo di sta storia degli artefatti per i verificatori, dovremmo specificare che ciò avviene solo in PR proprio perché li avviene la verifica

# 3.4.2
Vedi 3.4
Inoltre, il test viene eseguito anche in Action. In locale è solo se vogliamo (anzi, dovremmo). La action è un check in più in caso di inosservanza di qualcuno

# 3.6
AHAHAHAHAHA

Nonostante il wall of text, fatto bene come contenuto. Ci sta

2024-11-25 10:03 UTC, MarinDavide requested changes
Ovviamente d'accordo sulle correzioni tecniche di @klamerja, aggiungo ciò che ho trovato, si tratta semplicemente di termini da mettere in corsivo e typo:

## 3.1
- "software" da mettere in corsivo

## 3.1.3.5
- In "Descrizione", "issue" è da mettere in corsivo

## 3.1.8
- In "Sottolineatura", "issue" è da mettere in corsivo

## 3.2.1
- "contenente i file necessari", "file" è da mettere in corsivo

## 3.2.4
- typo: nell'ultima frase del paragrafo, "in questa operzione" manca la a di "operazione"

## 3.4
- "pull request" e "ticketing" sono da mettere in corsivo

2024-11-25 15:09 UTC, DavidePicc commented on rtb/norme_di_progetto_ver2.0.0.typ
> +- *Verbali Interni*: [NOR] riunione, dove NOR indica il numero ordinale della rionione (ad esempio Prima o Dodicesima).
Hai scritto "rionione"

2024-11-25 16:27 UTC, ErPreco commented
Grazie per le correzioni, mi perdo parecchie cose. @klamerja rispondo a qualche punto
# 3.1.1.2
- non ho capito perché non dovrebbe andare bene, il glossario come tutto ciò che va modificato deve essere verificato
#3.2.1
- ci sta, ne possiamo parlare un attimo domani/mercoledì
# 3.2.1.1 
- sì è che non mi piaceva dire "ignora alcuni file", ho preferito stare più generico perché alla fine viene comunque coinvolto dalla action
# 3.2.1.2
- sì ma ignora i file in una precisa azione, quella della compilazione no? (discorso uguale al 3.2.1.1)
# 3.2.6
- quale parte del glossario?
# 3.4
- verifica e validazione andranno aggiornati più avanti specialmente con gli effettivi test che faremo sul codice dopo adr e design

2024-11-25 16:47 UTC, klamerja commented
> non ho capito perché non dovrebbe andare bene, il glossario come tutto ciò che va modificato deve essere verificato

Due cose non capisco... se ti riferisci a Glossario come documento o meno (e qui la mia nota sull'utilizzare i monospace)... detto ciò: se ciò così fosse, dovresti aggiungere il riferimento all'aggiornamento di `glossario.json`, non è solo il glossario ad essere aggiornato.
<hr>

> ci sta, ne possiamo parlare un attimo domani/mercoledì

va bene

<hr>


> * sì è che non mi piaceva dire "ignora alcuni file", ho preferito stare più generico perché alla fine viene comunque coinvolto dalla action

si ok, però è comunque sbagliato dire che è coinvolto dalle action perché non è così... non c'entra proprio niente

<hr>

> sì ma ignora i file in una precisa azione, quella della compilazione no? (discorso uguale al 3.2.1.1)

no, in `git add .` da locale

<hr>

> quale parte del glossario?

mi sembra quella del json solita

<hr>

> * verifica e validazione andranno aggiornati più avanti specialmente con gli effettivi test che faremo sul codice dopo adr e design

non penso di aver capito

2024-11-26 20:06 UTC, MarinDavide approved these changes

2024-11-26 20:07 UTC, DavidePicc approved these changes

2024-11-27 08:03 UTC, merged