Prima stesura `Analisi dei requisiti` con primi use cases
SWEatUNIPD/docs pull request #47
Opened 2024-11-25 13:09 UTC by MilanRiccardo03

2024-11-25 14:15 UTC, ErPreco commented
Annoto solo due cose riguardanti lo stile, la verifica la lascio a chi di ruolo:
1 Effettivamente il nome del progetto "NearYou - Smart custom advertising platform" è più evidente in corsivo quindi lo aggiungerò nelle NdP, in genere però i nomi dei prodotti non andrebbero in corsivo (questa sarà l'unica eccezione).
2 Mi piace riferirsi ai paragrafi usano il numero della sezione al posto del nome, aggiungo anche questo nelle NdP.
3 In 1.4 Attenti che il monospace va solo per i file, Norme di Progetto è diverso da norme_di_progetto.typ (il secondo va in monospace perché è il file). Stesso vale per il Glossario.
4 Attenti anche a tutti i termini in inglese (tipo database).

2024-11-25 14:52 UTC, MilanRiccardo03 commented
> Annoto solo due cose riguardanti lo stile, la verifica la lascio a chi di ruolo: 1 Effettivamente il nome del progetto "NearYou - Smart custom advertising platform" è più evidente in corsivo quindi lo aggiungerò nelle NdP, in genere però i nomi dei prodotti non andrebbero in corsivo (questa sarà l'unica eccezione). 2 Mi piace riferirsi ai paragrafi usano il numero della sezione al posto del nome, aggiungo anche questo nelle NdP. 3 In 1.4 Attenti che il monospace va solo per i file, Norme di Progetto è diverso da norme_di_progetto.typ (il secondo va in monospace perché è il file). Stesso vale per il Glossario. 4 Attenti anche a tutti i termini in inglese (tipo database e dashboard).

La pull request è ancora in draft (non ancora pronta da revisionare), comunque grazie mille del feedback, così arricchiamo anche le ndp

2024-11-25 16:45 UTC, MilanRiccardo03 commented
@ErPreco @DavidePicc, da come stiamo strutturando l'analisi dei requisiti ci saranno da aggiungere cose alle NdP:
 - [ ] struttura dei casi d'uso segue indicazioni del prof. Cardin (vedi slide) https://www.math.unipd.it/~rcardin/swea/2022/Diagrammi%20Use%20Case.pdf
 - [ ] struttura folder progetto per includere i diagrammi dei casi d'uso (vedi snippet sotto)
 - [ ] nomenclatura diagrammi dei casi d'uso (vedi snippet sotto)
```
.
├── .github/
├── .vscode/
├── assets/
│   ├── font/
│   ├── img/
│   └── use_cases/
│       ├── UC1.svg
│       ├── UC2.svg
│       ├── UC3.svg
│       ├── UC4.svg
│       └── UC5.svg

```

2024-11-25 17:21 UTC, ErPreco commented
> @ErPreco @DavidePicc, da come stiamo strutturando l'analisi dei requisiti ci saranno da aggiungere cose alle NdP:
> 
> * [ ]  **forse da aggiungere** strumento per disegnare i diagrammi dei casi d'uso: draw.io
> * [ ]  struttura dei casi d'uso segue indicazioni del prof. Cardin (vedi slide) https://www.math.unipd.it/~rcardin/swea/2022/Diagrammi%20Use%20Case.pdf
> * [ ]  struttura folder progetto per includere i diagrammi dei casi d'uso (vedi snippet sotto)
> * [ ]  nomenclatura diagrammi dei casi d'uso (vedi snippet sotto)
> 
> ```
> .
> ├── .github/
> ├── .vscode/
> ├── assets/
> │   ├── font/
> │   ├── img/
> │   └── use_cases/
> │       ├── UC1.svg
> │       ├── UC2.svg
> │       ├── UC3.svg
> │       ├── UC4.svg
> │       └── UC5.svg
> ```

Sicuramente, grazie dell'elenco che faciliterà l'aggiornamento delle NdP. Per ora lascerei che si approvi questa versione così anche da vedere se sorgono complicanze col merge, successivamente andrà aggiornato.

2024-11-26 12:13 UTC, DavidePicc requested changes
Il documento è esterno, ma gli unici destinatari siamo noi. Non penso sia corretto. Infatti dopo scrivete "Il documento quindi è rivolto ai membri del gruppo di progetto e ai committenti" quindi penso sia più sensato lasciarlo esterno, ma mettere i committenti tra i destinatari.

Inoltre avete scritto nel glossario che va evidenziata solo la prima occorrenza del termine, ma "GenAi" ha la g per ben 3 volte.

 # 1.4
> 3 In 1.4 Attenti che il monospace va solo per i file, Norme di Progetto è diverso da norme_di_progetto.typ (il secondo va in 
 monospace perché è il file)

Norme di progetto e Glossario sono ancora scritti, erroneamente, in monospace

# 2.1 DA CAPIRE
> "Il prodotto ha come obiettivo quello di fornire un servizio di pubblicità personalizzata _integrato in una mappa, accessibile agli  utenti di un mezzo a noleggio_, che sfrutta la tecnologia GenAIg per la creazione di pubblicità mirate sui singoli utenti."

Non mi piace molto la parte che ho evidenziato in corsivo, se fossi un esterno non so se capirei cosa fa il progetto. 
In compenso l'avete spiegato molto bene nella sezione **2.3**, vi direi di prendere spunto ed o spiegare bene sia cosa dobbiamo fare per l'utente e per il gestore; oppure di non andare in dettaglio con nessuno dei due, dato che lo spiegate dopo.  (Io propenderei per la prima)

"Dashboard" essendo in inglese dovrebbe essere in corsivo. Stessa cosa per "database".

# 3.2
> Amministratore: gestore di un servizio di noleggio che, perciò, avrà accesso alla dashboard, senza
bisogno di autenticazione.

Toglierei "Senza bisogno di autenticazione", penso che per forza dovrà autenticarsi in qualche modo. Ma non essendone sicuro lo toglierei e basta, senza specificare se deve o non identificarsi.

E poi in **3.3.3** ed in **3.3.4** avete scritto:
>Precondizioni: l’amministratore del sistema è autenticato e ha accesso alla dashboard grafana

# 3.3.2 
Visivamente non mi piace che la figura sia in una nuova pagina (che contiene solo quella). Metterei un brakepage prima di questa sezione (e se abbastanza grandi in generale prima di ogni sezione di un caso d'uso)

---

Per il resto il documento mi sembra ben fatto, i casi d'uso soprattutto.
Un bel documento che dice quello che deve dire senza troppi giri di parole.

2024-11-26 16:10 UTC, MilanRiccardo03 commented
- [ ] attori: aggiungere llm e sensore
- [ ] casi d'suo: UC1 è fattto dai sensori, llm riceve i dati e genera il messaggio per mandarlo al sistema
- [ ] l'utente deve autenticarsi? E l'admin? in caso sono più casi d'uso
- [ ] sistemare svg UC2 
- [ ] alcuni use cases forse si posso "ampliare", detro a un rettangoo più ovali, ad esempio visualizzazione dashboard amministratore può diventare visualizzazione interazioni e dentro lì il singolo ovale può essere visualizza dettaglio singola interazione (aggiungere commento nel file adr)

2024-11-27 07:49 UTC, MarinDavide requested changes
Ho trovato qualche modifica rapida da fare:

## Tabella versioni
- Va invertito l'ordine delle righe, devono essere dalla versione più recente alla meno recente come fatto finora nei documenti.

## 2.1
- "database" da mettere il riferimento al glossario

## 2.4
- Domanda, NiFi non va aggiunto?
- "GPS" da mettere il riferimento al glossario
- "LLM" da mettere il riferimento al glossario

## 3.2
- LangChain è già stato riferito a Glossario prima, nel 2.4

## 3.3.3
- "marker" da mettere in corsivo

## 3.3.4
- In Postcondizioni, "feedback" da mettere in corsivo

## 3.3.5
- In Postcondizioni, "feedback" da mettere in corsivo
- In Scenario Principale, "feedback" da mettere in corsivo

2024-11-27 14:12 UTC, MarinDavide commented
Ho visto che è stata aggiunta una versione 1.2.0, ma non essendo stata ancora approvata la 1.1.0 dovrebbe rimanere quella @davim02 .

2024-11-27 14:59 UTC, davim02 commented
> Ho visto che è stata aggiunta una versione 1.0.2, ma non essendo stata ancora approvata la 1.0.1 dovrebbe rimanere quella @davim02. Anzi, forse essendo che è stato aggiunto Nifi, sarebbe da cambiare quella riga in 1.1.0 che diventa quindi modifica minor e non più solo patch

Giusto, dovrei aver sistemato

2024-11-27 18:29 UTC, ErPreco commented
# 2.1
- Benefit in corsivo

# 2.3
- Flotta? non dico sia sbagliato solo non capisco cosa intendiate

# 2.4
- Script metterei in minuscolo perché è un nome generico (e inglese quindi anche in corsivo)

# 3.2
- Sostituire i ";" con i "." (vedi NdP)
- Renderei più fluida la frase scrivendo  […] che avrà quindi accesso […]

# Su tutti i casi d'uso
- mettere i "." sulle voci degli elenchi con una frase (le singole parole tipo gli attori possono rimanere così, vedi NdP)
- le immagini hanno stili diversi

# 3.3.2
- Display in corsivo

# 3.3.3
- L'attore andrebbe in maiuscolo vedendo i casi d'uso precedenti

# 3.3.4
- Grafana in maiuscolo

2024-11-27 21:09 UTC, MarinDavide approved these changes

2024-11-28 09:00 UTC, DavidePicc commented
Ma è voluto che le immagini partano dalla 2 ? Per il resto va bene

2024-11-28 14:43 UTC, MilanRiccardo03 commented
> Ma è voluto che le immagini partano dalla 2 ? Per il resto va bene

Come ho risposto su telegram, è un problema da risolvere nel template. Quindi in questa pr si può ignorare l'errore. Grazie di aver portato all'occhio il problema.

2024-11-28 14:43 UTC, DavidePicc approved these changes

2024-11-29 14:10 UTC, merged