Primo commit del PdP
SWEatUNIPD/docs pull request #52
Opened 2024-11-27 17:11 UTC by klamerja

2024-11-27 17:44 UTC, MarinDavide requested changes
## Tabella versioni
- La versione non la terza cifra
- Da aggiungere anche Picello nei verificatori (anche in prima pagina)
- Aggiungerei tutto quello che hai fatto oltre l'introduzione

## 1.2
- "bike-sharing" sarebbe da mettere in corsivo

## 2.1.1
- feedback non è nel glossario (?)

## 2.1.2
- "item" da mettere in corsivo
- "backlog" da mettere in corsivo

## 2.2.1
- deep dive da mettere in corsivo

## 3
- "software" da mettere in corsivo
- "sprint" da mettere in corsivo
- "feedback" da mettere in corsivo

## 4
- molti "sprint" da mettere in corsivo, 7 volte se ho contato giusto
- Ultimo paragrafo, cambiare "I sprint" con "Gli sprint"

## 4.1.1
- "sprint" da mettere in corsivo

## 4.1.1.1
- "sprint" da mettere in corsivo

## 4.1.1.2 e 4.1.1.3
- Mancano delle ore

## 4.1.1.4
- Da aggiungere prima del merge (?)

2024-11-27 20:23 UTC, klamerja commented
# Tabella versioni
✅

# 1.2
✅

# 2.1.1
Va aggiunto, devo anche chiedere sul gruppo per quanto riguarda i nuovi termini da aggiungere.

# 2.1.2
Ho rimosso item e modificato backlog come specificato

# 2.2.1
Messo in corsivo e aggiunto al glossario (già presente)

# 3
Feedback messo in corsivo e aggiunto un occorrenza al glossario (da aggiungere)
software è stato rimosso per refactoring
sprint (come i punti a venire) l'avevo pensato come termine abbastanza utilizzato anche nel vocabolario italiano (potrei sbagliarmi, quindi chiedo conferma). Nel dubbio te lo refactoro in corsivo

# 4
Non trovo "I sprint"... potrei averlo rimosso inconsciamente a seguito del refactoring.
Per quanto riguarda lo sprint in corsivo, non è proprio bello da vedere il bold con l'italic (dopo **rischi attessi**) => chiedo conferma a te

Per le ore invece, era la vecchia versione pushata prima di revisionare di nuovo l'excel (grazie comunque della nota).

# Glossario
Ho individuato i seguenti termini
- feedback
- sprint (potrei evitarlo, visto che nel modello software e nella pianificazione viene anche chiamato con iterazione)
- bike-sharing (sono indeciso)

2024-11-27 21:02 UTC, MarinDavide requested changes
Sono d'accordo sui termini ormai molto usati in italiano, però non vorrei poi risultassero come nostre mancanze se non tutti li reputano "inglobati" nella lingua.
Comunque, correzioni da applicare trovate: 

## 1.2
- "bike-sharing" da riferire al glossario

## 4
- "I sprint" è scritto sull'ultimo paragrafo del 4
![image](https://github.com/user-attachments/assets/0f6a888e-07b9-4637-9234-fa60e554be11)

## 4.1.1.2 e 4.1.1.3
- Nelle ore, le mie sono state messe come programmatore invece di verificatore

## 4.1.1.4
- Mi odierai, ma ci sono termini da mettere in corsivo: "branch" e "file" nel secondo paragrafetto
- L'ultimo appunto sui verificatori, può anche essere lasciato così, ma forse sarebbe meglio girarla al "positivo", cioè tipo "suggeriscono di incaricare tutti quelli disponibili per una verifica ottimale".

2024-11-27 21:19 UTC, klamerja commented
> Sono d'accordo sui termini ormai molto usati in italiano, però non vorrei poi risultassero come nostre mancanze se non tutti li reputano "inglobati" nella lingua.

Si infatti li ho aggiunti tutti alla fine. Grazie comunque del parere.



> Nelle ore, le mie sono state messe come programmatore invece di verificatore

Faccio mea culpa e procedo a fixare (purtroppo le colonne dell'excel con quelle del piano sono in ordine diverso)



> Mi odierai, ma ci sono termini da mettere in corsivo: "branch" e "file" nel secondo paragrafetto

No problem, anzi meglio siccome non me ne ero accorto. Avrei anche il dubbio

> L'ultimo appunto sui verificatori, può anche essere lasciato così, ma forse sarebbe meglio girarla al "positivo", cioè tipo "suggeriscono di incaricare tutti quelli disponibili per una verifica ottimale".

provvedo a lavorarci

2024-11-27 21:39 UTC, MarinDavide requested changes
sempre senza rancore...

## 4 
- sempre "I sprint" da cambiare... 
![image](https://github.com/user-attachments/assets/ae354e61-11f5-4d63-832f-8bce53126122)

## 4.1.1.3
- Le mie ore anche qua andavano messe da verificatore

2024-11-27 21:40 UTC, klamerja commented
Chiedo scusa, piccola distrazione. 2 min e pusho

2024-11-27 21:54 UTC, MarinDavide approved these changes

2024-11-28 08:31 UTC, MarinDavide approved these changes

2024-11-28 09:28 UTC, DavidePicc commented
@klamerja 

# 2.1.2
Nella sezione 2.1.2 il titolo parla di sovrastima, mentre la descrizione di sottostima

>2.1.2. Sovrastima della durata delle attività
ID Rischio RO-2
Descrizione Data l’inesperienza del gruppo, specie ad inizio progetto, è possibile che alcune attività possano essere sottostimate in termini di tempo. Ciò porta ad un termine anticipato dell’attività stessa rispetto a quanto preventivato

---
# 3
> soddisfare al più possibile

Non penso sia corretto dire "al più possibile"

2024-11-28 09:36 UTC, klamerja commented
> Nella sezione 2.1.2 il titolo parla di sovrastima, mentre la descrizione di sottostima

Colpa mia, quando ho fixato ho dimenticato di cambiare sottostima con sovrastima




> Non penso sia corretto dire "al più possibile"

Cambiato con "il più possibile"

2024-11-28 09:38 UTC, DavidePicc approved these changes

2024-11-28 09:41 UTC, merged