Prima stesura VI_2024-11-28
SWEatUNIPD/docs pull request #58
Opened 2024-11-28 16:42 UTC by DavidePicc

Close #49

2024-11-29 13:28 UTC, ErPreco requested changes
Attento in generale a non enfatizzare le parole se non necessario (tipo Sprint o Novembre quando invece vanno con la minuscola), anche perché alcune volte le metti altre no.

# 2
- Consiglio si semplificare un pelo la prima frase nel seguente modo: Dopo l’incontro di fine sprint con l’azienda il 27 novembre, in cui sono stati chiariti vari dubbi, il gruppo si è confrontato internamente.
- Il secondo paragrafo sarebbe da rivedere sia perché ripete che abbiamo discusso le attività del prossimo sprint, sia perché la retrospettiva (sono stati analizzati i progressi raggiunti) non dovrebbe essere inclusa nel VI (che infatti dovrebbe iniziare alle 5.10) da quel che ho capito.

# 3
- L'OdG dovrebbe essere diviso in paragrafi (vedi gli scorsi VI)
- Dovrebbe privilegiare la spiegazione della motivazione delle scelte, non solo quali abbiamo preso (che sono riportate copia incolla nella tabella). Ad esempio il primo punto sul Gantt è buono perché spiega la necessità di cercarne uno diverso da GitHub. Mi focalizzerei sul perché dobbiamo creare l'infrastruttura docker, che vantaggi ha, come ci siamo divisi nello sprint (prima settimana studio e seconda settimana buildare qualcosa). Altro punto importante sono i casi d'suo: perché vanno sistemati, cosa va aggiunto/tolto e perché. Uguale il PdQ, perché e a cosa serve. Non mi soffermerei troppo su chi fa cosa ma cosa comportano certe scelte.
- … Gantt alternativi a Githubg. In quanto quest’ultimo …, In quanto non può iniziare una frase
- Sempre per il Gantt scriverei i consigli che sono saltati fuori (ricordo solo Gantt Project)
- Aggiungerei Gantt al glossario

# 4
- Per il prossimo sprint si punta, quindi, ad: quindi non può stare "da solo"
- Privilegerei un paragrafo discorsivo come gli scorsi verbali piuttosto di un elenco puntato

2024-11-29 14:56 UTC, ErPreco commented
Ricordo inoltre di aggiungere le decisioni (e quindi creare le issue per):
1 template klaudione
2 modifica NdP da parte mia per il versioning

2024-11-29 17:33 UTC, DavidePicc commented
Rimane da scrivere la parte sul template (aspetto che @klamerja mi dica precisamente cos'è stato modificato).

Intanto mando per verificare il resto.

Il paragrafo 4 l'ho scritto così. Sembra ancora un po' un elenco puntato, ma mi sembra più chiaro.

2024-11-29 18:41 UTC, ErPreco commented
Molto migliorato l'OdG e le conclusioni, annoto alcune modifiche di carattere generale seguite da alcune specifiche.

- sprint in corsivo
- versioning in corsivo
- i mesi vanno in minuscolo, è l'inglese che gli mette la maiuscola (in generale attento al typing di maiuscole, non solo per i mesi)

# 3.1
- direi più "alternativi a quello fornito da GitHub", scritta così sembra che GitHub sia un sistema per Gantt (dimenticato di segnalare prima)

# 3.2
- più che studiare Docker (sicuramente anche quello) dovremmo studiare come creare una infrastruttura con Kafka e Nifi (da quel che ho capito solo questi due, chiedo conferma a @MilanRiccardo03 )

# 3.3
- Aggiungere il "." a fine elenco (vedi NdP) e alla fine del paragrafetto sotto.
- Norme di Progetto scritto così, sto aggiornando le NdP in modo che sia più chiaro (il titolo del documento è ancora Norme di progetto e può fuorviare ma sto appunto cambiando)
- Aggiungerei il perché abbiamo deciso di cambiare versioning, il discorso dei responsabili

# 3.4
- Piano di Qualifica scritto così
- Come sempre nei verbali andrebbe scritto il perché stiamo iniziando il PdQ oltre alla definizione (comunque non presenta solo le procedure di verifica e validazione). Scriverei ad esempio che per il carico che avevamo abbiamo privilegiato le NdP e il PdP, ora che Tullio ha iniziato a parlarne ci è sembrato opportuno iniziare quanto meno.

# 3.6
- Piano di Progetto scritto così
- Manca il "." a alla seconda voce

# 3.7
- Eviterei un paragrafo per questo, non lo abbiamo mai messo visto che più che una decisione è una prassi

# 4
- Analisi dei Requisiti scritto così (anche PdP e PdQ)

2024-11-30 10:51 UTC, ErPreco commented
# 2
- Anche sprint del rifGlossario va in corsivo
- Come già detto eviterei il secondo paragrafo perché ripete quanto detto nel primo, al massimo lo integrerei al primo in altro modo.

# 3.1
- Gantt è il nome proprio del tipo che lo ha inventato, "diagramma" no, non va in maiuscolo (come hai sempre scritto nel resto del documento)

# 3.3
- Come notato precedentemente manca la spiegazione del problema dei responsabili (quindi delle approvazioni) che è la principale ragione del perché abbiamo cambiato versioning. Anche il fatto che il responsabile deve dare priorità al PdP e in caso l'amministratore si occuperà di redigere alcuni documenti al posto suo
- Major, Minor e Patch dovrebbero essere nomi comuni quindi in minuscolo
- Norme di Progetto alla fine

# 3.5
- team in corsivo

# 3.6
- sprint non in corsivo nei titoli per fattore estetico (vedi NdP)

# 4
- template in corsivo

# 5
- Andrea deve informarsi sul Gantt, non tutto il gruppo
- Io e Riki (non ho capito se anche @klamerja) dobbiamo studiare Docker, non tutto il gruppo
- Le descrizioni delle issue devono corrispondere ai titoli delle issue (vedi NdP)
- Ieri abbiamo deciso che dovrai scrivere te il PdP come responsabile, non Andrea (che ora è amministratore)
- Si visualizza _sprint_ ma non è in corsivo
- Martinelli deve iniziare il PdQ, non Marin
- Norme di Progetto
- versioning in corsivo

2024-12-01 11:09 UTC, DavidePicc commented
# 5
> Major, Minor e Patch dovrebbero essere nomi comuni quindi in minuscolo (sto aggiornando anche nelle NdP)

Infatti avevo guardato da là. Ora ho messo in minuscolo tranne nell'elenco perchè sono la prima parola della frase. Confermami che è corretto.

> - Si visualizza sprint ma non è in corsivo
> - Versioning in corsivo

Noto che nella tabella il corsivo non lo prende :(

# Extra
Mi sono pentito di aver scelto di mettere in corsivo tutti i termini inglesi. Troppo facile dimenticarsi di modificare lo stile ad alcune parole che ormai usiamo tutti i giorni come "team"

2024-12-01 11:23 UTC, ErPreco commented
> # 5
> > Major, Minor e Patch dovrebbero essere nomi comuni quindi in minuscolo (sto aggiornando anche nelle NdP)
> 
> Infatti avevo guardato da là. Ora ho messo in minuscolo tranne nell'elenco perchè sono la prima parola della frase. Confermami che è corretto.
> 
> > * Si visualizza sprint ma non è in corsivo
> > * Versioning in corsivo
> 
> Noto che nella tabella il corsivo non lo prende :(
> 
> # Extra
> Mi sono pentito di aver scelto di mettere in corsivo tutti i termini inglesi. Troppo facile dimenticarsi di modificare lo stile ad alcune parole che ormai usiamo tutti i giorni come "team"

- Confermo

- Puoi passare il contenuto tra quadre senza virgolette, così puoi aggiungere gli stili (ad esempio [_team_])

2024-12-03 16:10 UTC, ErPreco commented
Riporto le ultime migliorie da apportare dal punto di vista stilistico.

# Registro delle modifiche
- la data deve corrispondere a quella di ultima modifica (vedi NdP)

# Riassunto
- sprint in corsivo x2 (aspettare il nuovo template)
- non c'è il "." a fine frase

# 3.3
- le voci con frasi terminano col "." (vedi NdP)

# 3.6
- team in corsivo

# 5
- se vuoi andare a capo coi nomi conviene usare questi due metodi che evitano lo spazio vuoto
	- [Andrea Precoma \ Riccardo Milan] (passato per contenuto)
	- "Andrea Precoma\nRiccardo Milan" (passato per stringa)

2024-12-03 20:16 UTC, DavidePicc commented
> le voci con frasi terminano col "." (vedi NdP)

Io avevo guardato proprio dalle NdP dove tu hai scritto con il punto e virgola:
>• X (Major): Aggiunta di nuovi contenuti, paragrafi o cambiamenti consistenti al testo;
• Y (Minor): Aggiornamento di porzioni di testo consistente ma che era già presente;
• Z (Patch): Aggiustamento dello stile del testo, ortografico e decorativo.

Le correzioni sono state apportate tranne mettere sprint in corsivo sul Riassunto, in attesa del nuovo template. Intanto ho pushato per salvare le modifiche.

2024-12-04 14:21 UTC, ErPreco commented
> > le voci con frasi terminano col "." (vedi NdP)
> 
> Io avevo guardato proprio dalle NdP dove tu hai scritto con il punto e virgola:
> 
> > • X (Major): Aggiunta di nuovi contenuti, paragrafi o cambiamenti consistenti al testo;
> > • Y (Minor): Aggiornamento di porzioni di testo consistente ma che era già presente;
> > • Z (Patch): Aggiustamento dello stile del testo, ortografico e decorativo.
> 
> Le correzioni sono state apportate tranne mettere sprint in corsivo sul Riassunto, in attesa del nuovo template. Intanto ho pushato per salvare le modifiche.

A quanto pare hai guardato la versione vecchia, c'è una PR aperta dedicata proprio agli aggiornamenti (tra cui questo). Appena verrà approvata dovrei aver finito di metterci le mani.

Per lo stesso motivo del VE chiedo a @MilanRiccardo03 di approvare questo documento a fine mia revisione così da potersi mettere come responsabile. Chiedo perciò di apportare questi ultimi accorgimenti:

- mettere Riccardo Milan come responsabile
- col nuovo template ora è possibile aggiustare i corsivi nel riassunto

# 5
- nella D0060 test va messo in corsivo

2024-12-04 21:36 UTC, DavidePicc commented
In **3.8 Miglioramento _test_ del glossario** non ho messo il riferimento al glossario alle parole Git e Backlog in quanto usate come esempio, parole di cui non ci importa il significato. Ho anche usato le virgolette perchè mi sembrava più chiaro, per far capire che quelle parole vengono prese come singole, e non confonderle nel testo, anche se non è scritto tra i casi nelle NdP.

@ErPreco dimmi se ho fatto bene o no.

2024-12-05 15:30 UTC, ErPreco commented
Capisco essere degli esempi però per evitare falsi positivi aggiungere il riferimento. In genere è pensato per chiarire quel termine indipendentemente dal contesto.

Ricordo poi due cose spiegate nelle NdP:
- nei titoli non deve essere usato il corsivo
- i comandi (in questo caso #backlog()) vanno in monospace

2024-12-05 18:43 UTC, DavidePicc commented
Speriamo sia la volta buona @ErPreco

2024-12-05 19:16 UTC, ErPreco approved these changes

2024-12-05 19:16 UTC, ErPreco commented
Chiedo l'approvazione di @MilanRiccardo03

2024-12-06 15:47 UTC, MilanRiccardo03 commented
> Chiedo l'approvazione di @MilanRiccardo03

Approvazione concessa, ci siamo

2024-12-06 15:49 UTC, merged