Migliorie template
SWEatUNIPD/docs pull request #62
Opened 2024-12-02 18:14 UTC by klamerja

Vi chiedo di porre particolare attenzione ai file modificati per verificare che non vi siano documenti con difetti.

Sto rilevando in alcuni file che mancano delle definizioni nel glossario, parole anche di un certo peso. Vi chiedo conferma anche per quanto riguarda quelle.

Inoltre, per il verbale esterno che Sync Lab aveva già firmato, direi di aggiungere una versione per motivare le modifiche che richiedono una nuova firma

2024-12-02 21:05 UTC, ErPreco requested changes
# VE_2024-11-13
# 2
- best practice in corsivo
- milestone in corsivo
- repository in corsivo

# 3.1
- Analisi dei Requisiti
- vedi correzione 4.1 del VI_2024-11-13

#3.2
- best practicec in corsivo
- GitLab potrebbe andare nel glossario
- Docker Compose e Kubernetes potrebbe andare nel glossario
- Minimum Viable Product non andrebbe in corsivo (incoerenza a priori con Proof of Concept)
- milestone in corsivo

# 4
- team in corsivo
- storage in corsivo


# VE_2024-11-20
# 2
- step in corsivo
- TimeScale è scritto così nel glossario, quindi andrebbe anche referenziato
- focus in corsivo

# 3.4
- database in corsivo

# 4
- Mock-up in corsivo (da aggiungere al glossario?)


# VI_2024-11-10
# 2.1
- e-mail in corsivo

# 2.3
- backlog in corsivo
- issue in [#ID issue] in corsivo
- repository in corsivo x3
- issue in corsivo

# 2.6
- repository in corsivo
- file standard in corsivo

# 3
- wow in corsivo e in minuscolo (non è un documento)

# 4
- e-mail
- Glossario


# VI_2024-11-13
# Registro modifiche
- camel-case in corsivo

# 4.1
- nel glossario avevamo scelto di mettere stream processing, non so se ci sono differenze con data streaming e data processing
- aggiungerei event-driven architecture
- andrebbero scritti Apache Kafka, Apache Nifi e Apache Flink col glossario

# 4.3
- accorcerei il titolo (Organizzazione degli incontri e tracciabilità decisioni)
- call in corsivo x3
- eviterei di ripetere "settimana" 4 volte in un'unica frase
- sprint in corsivo

# 5.2.1
- sarebbe data broker (glossario)
- database in corsivo

# 5.3
- si possono evitare le "" in Norme di Progetto

# 6
- framework in corsivo
- Analisi dei Requisiti

# 7
- issue in corsivo


# VI_2024-11-20
# 3.1
- 4° punto sprint non è in corsivo

# 3.6
- metterei Glossario del progetto
- test in corsivo

# 4
- Analisi dei Requisiti
- sprint in corsivo
- scriverei Rendicontazione ore, rendicontazione significa "conteggiare", da solo non significa nulla

2024-12-02 22:42 UTC, klamerja commented
> * Analisi dei Requisiti

solo il titolo?

> * vedi correzione 4.1 del VI_2024-11-13

in questo caso aveva senso anche stream processing, ma evito siccome era solo per lo stile... non so se inserirlo a verbale

> * Minimum Viable Product non andrebbe in corsivo (incoerenza a priori con Proof of Concept)

Colpa mia... ma a questo punto converebbe metterli entrambi, no?

> * milestone in corsivo

non lo vedo

> * Analisi dei Requisiti

anche dove viene utilizzato come cosa da fare e non come documento?



> * TimeScale è scritto così nel glossario, quindi andrebbe anche referenziato

eh...

> * Mock-up in corsivo (da aggiungere al glossario?)

tra l'altro si scrive mockup...



> * e-mail in corsivo

c'è un email anche in backlog. Per NdP va lasciato così o anche li corsivo?

> 4

ho sostituito PR con pull request

> * nel glossario avevamo scelto di mettere stream processing, non so se ci sono differenze con data streaming e data processing

allora, son due fasi che compongono lo stream processing, vero anche che però così devi mettere i due termini a vocabario. Rimpiazzo


> * andrebbero scritti Apache Kafka, Apache Nifi e Apache Flink col glossario

non è apache kafka, ma kafka streams che è "diverso" (e qui dico: la aggiungiamo a glossario)

> * eviterei di ripetere "settimana" 4 volte in un'unica frase

-1 ho fatto,

> * sarebbe data broker (glossario)

non ho capito

> * metterei Glossario del progetto

ho tolto "del progetto" (di cosa altrimenti?)

2024-12-02 22:42 UTC, klamerja commented
Avviso: Norme di progetto hanno warning perché utilizzate una codifica strana per l'apostrofo

2024-12-03 13:41 UTC, ErPreco commented
> > * Analisi dei Requisiti
> 
> solo il titolo?
- sì
> > * vedi correzione 4.1 del VI_2024-11-13
> 
> in questo caso aveva senso anche stream processing, ma evito siccome era solo per lo stile... non so se inserirlo a verbale
- va bene lascia così
> > * Minimum Viable Product non andrebbe in corsivo (incoerenza a priori con Proof of Concept)
> 
> Colpa mia... ma a questo punto converebbe metterli entrambi, no?
- sì forse conviene metterli in corsivo
> > * milestone in corsivo
> 
> non lo vedo
- scusa era al punto 3.3
> > * Analisi dei Requisiti
> 
> anche dove viene utilizzato come cosa da fare e non come documento?
- se non ti riferisci al documento no hai ragione, però non capisco a quale correzione ti riferisci, sempre al titolo del 3.1?
> > * TimeScale è scritto così nel glossario, quindi andrebbe anche referenziato
> 
> eh...
- dovrebbe aggiungerlo il redattore (come tutte le altre modifiche riguardanti il glossario per me) 
> > * Mock-up in corsivo (da aggiungere al glossario?)
> 
> tra l'altro si scrive mockup...
- ho visto potersi scrivere in entrambi i modi, se ti piace di più possiamo mettere mockup cambia poco
> > * e-mail in corsivo
> 
> c'è un email anche in backlog. Per NdP va lasciato così o anche li corsivo?
- non ho fatto distinzioni, le uniche che non vanno in corsivo sono quelle nei titoli
> > 4
> 
> ho sostituito PR con pull request
- non ho capito scusa
> > * nel glossario avevamo scelto di mettere stream processing, non so se ci sono differenze con data streaming e data processing
> 
> allora, son due fasi che compongono lo stream processing, vero anche che però così devi mettere i due termini a vocabario. Rimpiazzo
- ottimo
> > * andrebbero scritti Apache Kafka, Apache Nifi e Apache Flink col glossario
> 
> non è apache kafka, ma kafka streams che è "diverso" (e qui dico: la aggiungiamo a glossario)
- non sapevo pardon, sì aggiungerei che magari può essere confuso come è successo al sottoscritto ahah
> > * eviterei di ripetere "settimana" 4 volte in un'unica frase
> 
> -1 ho fatto,
- ottimo
> > * sarebbe data broker (glossario)
> 
> non ho capito
- che avrei scritto "data broker" al posto di solo "broker", così anche da collegarlo al glossario 
> > * metterei Glossario del progetto
> 
> ho tolto "del progetto" (di cosa altrimenti?)
- intendevo che Glossario dovrebbe andare con la maiuscola

2024-12-03 16:40 UTC, klamerja commented
> * se non ti riferisci al documento no hai ragione, però non capisco a quale correzione ti riferisci, sempre al titolo del 3.1?
> 
> > >

sì


> * non ho fatto distinzioni, le uniche che non vanno in corsivo sono quelle nei titoli
> 
> > >

ok come immaginavo... allora ho messo il corsivo

> * non ho capito scusa
> 
> > >

c'era pr scritto letteralmente PR, quindi l'ho sostituito (e qui non so se vada anche un termine a glossario)

> * che avrei scritto "data broker" al posto di solo "broker", così anche da collegarlo al glossario
> 
> > >

ok fatto



> * intendevo che Glossario dovrebbe andare con la maiuscola

sì avevo inteso, era una precisazione scusa

2024-12-03 16:44 UTC, ErPreco commented
> > * se non ti riferisci al documento no hai ragione, però non capisco a quale correzione ti riferisci, sempre al titolo del 3.1?
> > 
> > > >
> 
> sì
- capito allora sì lascia in minuscolo

> > * non ho capito scusa
> > 
> > > >
> 
> c'era pr scritto letteralmente PR, quindi l'ho sostituito (e qui non so se vada anche un termine a glossario)
- ah capito, no vabbe io eviterei di inserire anche pull request

2024-12-03 16:57 UTC, MilanRiccardo03 approved these changes
a parte i punti di @ErPreco mi sembra tutto apposto.

2024-12-03 19:03 UTC, ErPreco commented
Nell'AdR andrebbe aggiornato il changelog col nuovo versioning e rinominato.

Nell'introduzione del Glossario andrebbe tolto il monospace da `Glossario` e metterei la maiuscola a "glossario" alla fine.

Modifiche per il PdP:

# 2
- manca il "." alla fine
- gli elenchi devono terminare col "." (vedi NdP)
- nell'elenco numerato toglierei la punteggiatura di chiusura, o se vuoi lasciarla comunque va sostituita col punto

# 4
- sempre il punto alla fine delle voci dell'elenco

# 4.1.1.2
- avevo chiesto di mettermi 1h di programmatore prevista e segnare (+0.5) in quelle effettive perché è inverosimile avr pianificato 1.5h

2024-12-03 19:14 UTC, klamerja commented
> Nell'AdR andrebbe aggiornato il changelog col nuovo versioning e rinominato.

L'avevo lasciato per la prossima PR, ma va bene lo faccio adesso

> * manca il "." alla fine



> * manca il "." alla fine

si, me l'ero perso. Prossima volta specifica il paragrafo oppure usate la review da codice


> * gli elenchi devono terminare col "." (vedi NdP)

me l'ero persa. Mea culpa

> * nell'elenco numerato toglierei la punteggiatura di chiusura, o se vuoi lasciarla comunque va sostituita col punto

rimossa: per NdP roba corta non lo richiede, quindi mi attengo a quella allora

> * avevo chiesto di mettermi 1h di programmatore prevista e segnare (+0.5) in quelle effettive perché è inverosimile avr pianificato 1.5h

onestamente avevamo lasciato in sospeso per altri problemi, poi dopo non mi è stato più rinominato in questa PR. Provvedo a cambiare

<hr>

Io ora ricontrollo, ma siamo sicuri di non avere altri punti elenco con sto problema, tipo i verbali

2024-12-03 19:56 UTC, ErPreco commented
> Io ora ricontrollo, ma siamo sicuri di non avere altri punti elenco con sto problema, tipo i verbali

- sugli ultimi ho controllato di volta in volta e non mi sembra ci siano problemi

Mi sono dimenticato nel 4.1.1.1, alcune voci dell'elenco puntato sono delle frasi quindi andrebbero terminate col punto.

2024-12-03 21:14 UTC, ErPreco approved these changes

2024-12-03 21:16 UTC, merged