VE_2024-12-04_ver1.0.0
SWEatUNIPD/docs pull request #64
Opened 2024-12-05 09:28 UTC by Perruzz

close #63

2024-12-06 15:46 UTC, MilanRiccardo03 requested changes
Stile ottimo, contenuti da rivedere

2024-12-06 15:46 UTC, MilanRiccardo03 commented on rtb/verbali/esterni/VE_2024-12-04_ver1.0.0.typ
> +Durante l'incontro si è discusso di diversi aspetti per l'avanzamento del progetto. È stata pianificata la creazione del _#rifGlossario("database")_, che verrà popolato con dati falsi e strutturato i
- [ ] il docker esiste già, semmai bisogna migliorarlo
- [ ] l'integrazione del database con grafana è un punto importante e chiaro sin dall'inizio, non lo metterei qui
- [ ] aggiungerei il fatto che abbiamo parlato delle chiavi api per langchain su cui siamo bloccati e ci verrà dato supporto (se non ti ricordi chiedi su telegram)

2024-12-06 15:46 UTC, MilanRiccardo03 commented on rtb/verbali/esterni/VE_2024-12-04_ver1.0.0.typ
> +Per quanto riguarda i casi d'uso, continueremo a migliorarli e, se necessario, ne verranno scritti di nuovi. Parallelamente, verranno proseguite le seguenti attività di redazione:
- [ ] togli "se necessario", bisogna farne per forza di nuovi

2024-12-06 15:46 UTC, MilanRiccardo03 commented on rtb/verbali/esterni/VE_2024-12-04_ver1.0.0.typ
> +Alcuni dubbi sono stati chiariti durante l'incontro. Per quanto riguarda la struttura del _database_, si è concordato di suddividerlo in tabelle separate per rendere più semplice l'analisi e l'integr
- [ ] più che strutturare il database con tabelle separate (che è quasi scontato), il dubbio (che per altro non è ancora stato chiarito mi sembra) è se fare 2 database distinti per trattare le profilazioni e le posizioni gpx, oppure se mettere tutto in un unico db
- [ ] aggiungerei anche qui il discorso delle api di langchain che non funzionano, qui puoi chiedere a @klamerja più dettagli tecnici che ci ha lavorato (mi sembra il problema fosse che il processor usato è molto recente e ci sia poca documentazione
- [ ] aggiungerei il fatto che hanno dato feedback positivo rispetto a come stiamo lavorando su kafka e nifi

2024-12-06 15:46 UTC, MilanRiccardo03 commented on rtb/verbali/esterni/VE_2024-12-04_ver1.0.0.typ
> +- Configurazione dell'immagine con _Docker Compose_.
- [ ] c'è già, semmai è da migliorare (da chiedere a @klamerja )

2024-12-06 15:46 UTC, MilanRiccardo03 commented on rtb/verbali/esterni/VE_2024-12-04_ver1.0.0.typ
> +#infoRiunione(
- [ ] i partecipanti interni non devono includere Martinelli e Precoma che non hanno partecipato

2024-12-08 15:22 UTC, MilanRiccardo03 approved these changes
@ErPreco dato che sei l'altro revisore se vuoi approvare tu

2024-12-08 16:38 UTC, ErPreco commented
@MilanRiccardo03 avrebbe poco senso che io approvassi visto che non ero nemmeno presente. Essendo di ruolo chiedo a @DavidePicc di revisionare e approvare il documento (come ha correttamente segnato Andrea nel documento). Faccio notare tuttavia alcune correzioni secondo me opportune:

I nomi dei prodotti sw (Docker Compose, Apache Nifi ecc) non vanno in corsivo (vedi NdP)
I nomi dei documenti nel paragrafo 2 e 4 vanno in maiuscolo (vedi NdP)

# 2
- Cosa si intende con "immagine Docker Compose"? direi al massimo "la struttura creata con Docker Compose"

# 3
- Nella prima frase sostituirei il secondo "alcuni" con "parte" evitando la ripetizione
- Alla 4a riga metterei il punto tra in "unico database. La questione"

# 4
- scriverei "popolamento con dati fittizi"

2024-12-09 10:35 UTC, merged