Pdp pianificazione terzo sprint
SWEatUNIPD/docs pull request #80
Opened 2024-12-18 17:06 UTC by davim02

2024-12-19 14:56 UTC, davim02 commented
Siccome nel VI avevo scritto nelle decisioni che Riccardo si sarebbe occupato della dashboard ho pensato che forse è meglio lasciarlo anche nella pianificazione, poi nella retospettiva scriverò che invece si è occupato delle metriche perchè l'altra attività aveva delle dipendenze non ancora risolte. Poi ditemi voi se vi sembra una buona idea

2024-12-19 22:23 UTC, klamerja requested changes
Per il resto mi sembra fatto bene. Se trovo altri problemi al massimo riscrivo.
Siccome @DavidePicc ha sbagliato la tabella del preventivo, ovvero ha modificato quella del preventivo che serve alla funzione che genera il consuntivo ore per fare le differenze, dovresti "teoricamente" copia-incollare i dati del preventivo utilizzati dalla funzione di generazione del consuntivo e rimpiazzarlo ai dati della funzione di generazione del preventivo ore.
Grazie mille

2024-12-19 22:23 UTC, klamerja commented on rtb/glossario_ver0.11.0.typ
> +  redattori: ("Davide Picello", "Davide Marin", "Andrea Perozzo", "Andrea Precoma", "Riccardo Milan", "Klaudio Merja"),
Siccome avevamo fatto modifiche dopo aver aperto questa branch, ha ripristinato il vecchio ordine (sbagliato)

2024-12-19 22:23 UTC, klamerja commented on rtb/glossario_ver0.11.0.typ
> +  verificatori: ("Andrea Perozzo", "Andrea Precoma", "Davide Picello", "Riccardo Milan", "Davide Marin"),
Stesso problema anche qui

2024-12-19 22:23 UTC, klamerja commented on rtb/piano_di_progetto_ver0.4.0.typ
> +- *Rischi attesi*: #link(<RO-1>)[RO-1], #link(<RO-3>)[RO-3], #link(<RT-1>)[RT-1]
Piccola nota: se ne hai rischi da aggiungere, aggiungili pure

2024-12-19 22:23 UTC, klamerja commented on rtb/piano_di_progetto_ver0.4.0.typ
> +- Ampliamento del documento Norme di Progetto, in particolare occupandosi delle sezioni:
Viene segnato "Processi organizzativi" come aggiornamento. In realtà pure quello è un ampliamento. Non è ancora stato messo in main al momento in cui sto scrivendo.

2024-12-19 22:23 UTC, klamerja commented on rtb/piano_di_progetto_ver0.4.0.typ
> +  - Processi organizzativi
Il problema si rispecchia con quello che ho scritto prima

2024-12-19 22:23 UTC, klamerja commented on rtb/piano_di_progetto_ver0.4.0.typ
> +- In concomitanza con l'attività precedente, si procederà con lo studio di possibili metriche per la valutazione della qualità, che andranno al vaglio del gruppo
Purtroppo sto rompendo a tutti (colpa/merito di @ErPreco che da un lato ha anche ragione a non usare troppe virgole per introdurre pause a caso): la seconda virgola va rimossa sicuramente, la prima sono indeciso

2024-12-19 22:23 UTC, klamerja commented on rtb/piano_di_progetto_ver0.4.0.typ
> +- Continuazione del documento di Analisi dei Requisiti, che per questo _sprint_ si concentrerà sullo studio di nuovi casi d'uso, con l'obiettivo raccogliere eventuali nuovi dubbi da poter chiarire du
La seconda virgola la toglierei. La prima sempre indeciso

2024-12-19 22:23 UTC, klamerja commented on rtb/piano_di_progetto_ver0.4.0.typ
> +- Affinamento della _dashboard_ in Grafana effettuando migliorie di carattere estetico e/o funzionale.
metterei solo "e" invece di "e/o"

2024-12-20 11:32 UTC, davim02 commented on rtb/piano_di_progetto_ver0.4.0.typ
> +- In concomitanza con l'attività precedente, si procederà con lo studio di possibili metriche per la valutazione della qualità, che andranno al vaglio del gruppo
Ho tolto la prima e ho modificato leggermente la frase dopo la seconda. Mi suona più naturale così, poi non so ditemi voi

2024-12-21 16:12 UTC, klamerja requested changes
Non ho trovato altri problemi.
L'unica cosa che non posso riportati a codice in effettivo è lo spacing dell'elenco puntato siccome lasciate una riga di codice vuoto per ogni elemento dell'elenco puntato, facendo troppo spacing.
Se riesci a fixare ti ringrazio. Spero che @MarinDavide possa trovare altri problemi ond'evitare di ritrovarceli in consegna
<img width="531" alt="Screenshot 2024-12-21 at 17 10 58" src="https://github.com/user-attachments/assets/b6db00b3-2af8-4e95-8f8e-7d38d0237830" />

2024-12-21 16:12 UTC, klamerja commented on rtb/piano_di_progetto_ver0.4.0.typ
> +  redattori: ("Klaudio Merja", "Davide Picello", "Davide Martinelli"),
Ordine alfabetico dei nomi

2024-12-21 16:12 UTC, klamerja commented on rtb/piano_di_progetto_ver0.4.0.typ
> +  verificatori: ("Davide Marin", "Davide Picello", "Andrea Precoma", "Riccardo Milan", "Klaudio Merja"),
Ordine alfabetico dei nomi nuovamente

2024-12-23 12:45 UTC, MarinDavide approved these changes
Non ho trovato ulteriori problemi, per me si può approvare

2024-12-23 13:00 UTC, klamerja approved these changes

2024-12-23 14:50 UTC, merged