Casi d'uso NdP
SWEatUNIPD/docs pull request #83
Opened 2024-12-20 18:16 UTC by DavidePicc

closes #73

2024-12-20 18:18 UTC, DavidePicc commented
Ciao ragazzi, ho alcuni dubbi:
- Confermatemi che è inserito nella sezione giusta
- I titoli così come li ho messi hanno forse troppe cifre, dite che magari i 2.2.2.1.x ed 2.2.2.1.7.x posso trasformarli in semplicemente frasi in grassetto ?

2024-12-21 09:35 UTC, klamerja commented
Allora. Devo ancora iniziare effettivamente a leggere, ma riporto per messaggio: ricordo che altra gente ha fatto modifica con la stessa versione. Se dovesse capitare che qualcuno tira su prima di te la versione, quando mergi il main in questa branch fai attenzione a unire i due file del glossario e incrementare la minor del file del compagno a cui ha lavorato il glossario, altrimenti ci ritroviamo con due glossari come sempre in main. Grazie mille

2024-12-21 09:37 UTC, klamerja commented
Per quanto riguarda il glossario che a causa del json non prende la formattazione: fatto bene a mettere un sinonimo italiano di PM. Mi informo meglio settimana prossima su come risolvere

2024-12-21 10:35 UTC, klamerja requested changes

2024-12-21 10:35 UTC, klamerja commented on glossario.json
> +    "UML": "Unified Modeling Language, un linguaggio standardizzato di modellazione e di specifica basato sul paradigma orientato agli oggetti. Viene utilizzato per rappresentare componenti e le inte
acronimo di "Unified Modeling Language", è un linguaggio...

2024-12-21 10:35 UTC, klamerja commented on glossario.json
> +    "UML": "Unified Modeling Language, un linguaggio standardizzato di modellazione e di specifica basato sul paradigma orientato agli oggetti. Viene utilizzato per rappresentare componenti e le inte
per rappresentare **i** componenti e le...

2024-12-21 10:35 UTC, klamerja commented on assets/img/NdP/esempioUseCase2.png
Usare questa foto non è una bella idea. Lasciala pure intanto come placeholder, ma dobbiamo segnarci di modificarla, siccome io e @ErPreco siamo andati a chiedere conferma al prof (nonostante ci avesse risposto anche in parte giovedì) e questo diagramma non va bene teoricamente parlando

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +  verificatori: ("Andrea Precoma", "Davide Marin", "Davide Picello", "Klaudio Merja", "Riccardo Milan"),
Avevi fatto il verificatore degli use case? Non ricordavo

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +    "0.5.0",
Come per il glossario:  @MilanRiccardo03 sta modificando anche lui le NdP; attenzione a chi pusha prima e risolvere sto problema, altrimenti mi tocca andare a fixare in main

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +      - Scrittura della sezione "Casi d'uso"
Specifica anche in che processo secondo me. Vedi te comunque, non è nulla di necessario

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +In questa fase rientra la realizzazione dei casi d'uso (_use case_): descrizioni formali di come un sistema _software_ interagisce con utenti o altre entità, chiamati attori, per raggiungere un obiet
con altre entità "esterne al sistema". Lo specificherei, anche dopo aver ascoltato Cardin sottolinearlo più e più volte

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +In questa fase rientra la realizzazione dei casi d'uso (_use case_): descrizioni formali di come un sistema _software_ interagisce con utenti o altre entità, chiamati attori, per raggiungere un obiet
Buono il fatto di sottolineare il fatto di non specificare i dettagli implementativi

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +Gli attori rappresentano agenti esterni che interagiscono con il sistema. Ogni caso d'uso specifica una funzionalità creata per un determinato attore.
più che agenti direi entità. Vedi te comunque

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +===== Nomenclatura
Più che SOLO nomenclatura: abbiamo sia l'identificativo che la nomenclatura/titolo

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +- *Attore di supporto*: Un utente o _stakeholder_ coinvolto nel caso d'uso, ma che non inizia l'interazione con il sistema. Può fornire ulteriori input o risorse necessarie per completare lo _use cas
input in corsivo

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +- *Attore primario*: L'utente o _stakeholder_ che avvia il caso d'uso ed ha un obbiettivo da raggiungere utilizzando il sistema.
Piccolezza immonda: solitamente usi obiettivo con una "b". Quello che dico è: si, sono corretti entrambi, ma manterrei uno dei due invece che avere entrambe le varianti. Come vuoi te comunque, non è sbagliato assolutamente

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +Il _trigger_ rappresenta l'evento o l'azione che scatena il caso d'uso. Questo può essere un'azione compiuta da un attore, come un _clic_ su un pulsante, oppure un evento esterno come il ricevimento
click*

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +Il _trigger_ rappresenta l'evento o l'azione che scatena il caso d'uso. Questo può essere un'azione compiuta da un attore, come un _clic_ su un pulsante, oppure un evento esterno come il ricevimento
Che poi non vorrei dire cavolate, clic è un onomatopea italiana, quindi si potrebbe solo togliere il corsivo. Per tagliare la testa al toro ed essere insicuri, metti quello inglese

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +1. L'utente inserisce i dati di accesso.
Per quanto riguarda gli esempi, sempre una picolezza: starei sempre sullo stesso caso d'uso come esempio: in questo caso, per riferirci di più al nostro progetto, potresti fare la visualizzazione dashboard come esempio

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +- Un caso d'uso generico, come Gestire account, può essere specializzato in Creare account e Modificare account.
Più che creare, metterei eliminare

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +- Un caso d'uso generico, come Gestire account, può essere specializzato in Creare account e Modificare account.
Piccolezza nuovamente :)

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +Esempio: Un caso d'uso Autenticazione utente può essere incluso in casi d'uso come Acquista prodotto o Gestione profilo.
Allora. Me ne accorgo adesso ma vale anche per gli altri casi: le maiuscole non vanno utilizzate per questi casi. Però effettivamente non abbiamo una distinzione per il caso d'uso. Secondo me conviene che almeno li metti tra virgolette

2024-12-21 10:35 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +Nei casi d'uso possiamo avere i seguenti tipi di relazione tra attore e caso d'uso.
La numerazione troppo lunga secondo me non è un grande problema (per quanto mi anticipavi). Chiedo il riscontro anche di @MarinDavide

2024-12-21 12:13 UTC, MarinDavide commented on rtb/norme_di_progetto_ver0.5.0.typ
> +Nei casi d'uso possiamo avere i seguenti tipi di relazione tra attore e caso d'uso.
Si sono d'accordo, non è un problema

2024-12-21 14:13 UTC, klamerja requested changes

2024-12-21 14:13 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +Le estensioni definiscono variazioni opzionali o eccezioni al comportamento principale del caso d'uso. Questi flussi si attivano solo se si verificano determinate condizioni. Viene indicata nel diagr
<\<extend>> (in typst mi sembra che già i doppi apici vengano convertiti in doppie triangolari

2024-12-21 14:13 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +Le inclusioni rappresentano funzionalità o comportamenti comuni che possono essere riutilizzati in più casi d'uso per evitare duplicazioni. Viene indicata nel diagramma come una freccia tratteggiata
<\<include>>

2024-12-21 14:16 UTC, klamerja requested changes

2024-12-21 14:16 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
>    redattori: ("Klaudio Merja", "Andrea Precoma", "Davide Picello"),
Mettimi alla fine. Sono dopo di voi in ordine alfabetico

2024-12-21 14:35 UTC, klamerja commented
Ultima cosa: standard lasciamolo normale e non in corsivo

2024-12-22 12:29 UTC, klamerja requested changes

2024-12-22 12:29 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +Ogni caso d'uso deve essere identificato da un codice univoco, seguendo la nomenclatura: *UC[numero_use_case]*; seguito da un breve titolo esplicativo, separati da un trattino.
Problemino: metti come titolo "Nomenclatura" e mi dici che va un ID seguito da nomenclatura. Inizialmente avevo un'idea di separarli. Va bene anche unirli, ma per me il titolo non è del tutto coerente

2024-12-22 12:38 UTC, klamerja requested changes

2024-12-22 12:38 UTC, klamerja commented on glossario.json
> +    "UML": "Acronimo di \"Unified Modeling Language\", un linguaggio standardizzato di modellazione e di specifica basato sul paradigma orientato agli oggetti. Viene utilizzato per rappresentare i co
, **è** un linguaggio...

2024-12-22 12:38 UTC, klamerja commented on glossario.json
> +    "UML": "Acronimo di \"Unified Modeling Language\", un linguaggio standardizzato di modellazione e di specifica basato sul paradigma orientato agli oggetti. Viene utilizzato per rappresentare i co
Intendo dire che manca l' **è**

2024-12-22 15:17 UTC, DavidePicc commented on rtb/norme_di_progetto_ver0.5.0.typ
> +Ogni caso d'uso deve essere identificato da un codice univoco, seguendo la nomenclatura: *UC[numero_use_case]*; seguito da un breve titolo esplicativo, separati da un trattino.
C'è scritto "**seguendo** la nomenclatura". Nel senso "l'id si scrive così: ...".
Posso sostituirlo con "secondo la nomenclatura"

2024-12-22 20:28 UTC, klamerja requested changes

2024-12-22 20:28 UTC, klamerja commented on rtb/glossario_ver0.12.0.typ
> +    [- Aggiunto il termine "PostgreSQL", "Diagramma di Gantt"],
Meglio della virgola, usa "e"... piccolezza, vedi te se modificare

2024-12-22 20:28 UTC, klamerja commented on rtb/norme_di_progetto_ver0.5.0.typ
> +Ogni caso d'uso deve essere identificato da un codice univoco, secondo la nomenclatura: *UC[numero_use_case]*, seguito da un breve titolo esplicativo, separati da un trattino.
Allora... toglierei i due punti.

Dopo toglierei la virgola tra esplicativo e separati e metterei un "e"

2024-12-22 20:38 UTC, DavidePicc commented on rtb/norme_di_progetto_ver0.5.0.typ
> +Ogni caso d'uso deve essere identificato da un codice univoco, secondo la nomenclatura: *UC[numero_use_case]*, seguito da un breve titolo esplicativo, separati da un trattino.
Cambiato un po' la frase. Ora mi sembra meglio

2024-12-22 21:01 UTC, MarinDavide reviewed
Trovato piccolo typo, poi direi pronta per l'approvazione

2024-12-22 21:01 UTC, MarinDavide commented on rtb/norme_di_progetto_ver0.5.0.typ
> +In questa documento rientra la realizzazione dei casi d'uso (_use case_): descrizioni formali di come un sistema _software_ interagisce con utenti o con altre entità esterne al sistema, chiamati atto
Typo: "in questa documento" all'inizio del paragrafo

2024-12-22 21:13 UTC, MarinDavide approved these changes

2024-12-23 05:48 UTC, klamerja approved these changes

2024-12-23 12:31 UTC, klamerja commented
@davim02 puoi pure approvare

2024-12-23 12:33 UTC, merged