Stesura VI 23-12-24
SWEatUNIPD/docs pull request #94
Opened 2024-12-24 14:00 UTC by MilanRiccardo03

closes #85

2024-12-24 17:36 UTC, davim02 requested changes
Ultima piccolezza, forse metterei Indice di Gulpease (con il "di" in mezzo), quindi sarebbe da modificare sia nel VI che nel Glossario

2024-12-24 17:36 UTC, davim02 commented on rtb/verbali/interni/VI_2024-12-23_ver1.0.0.typ
> +All'ordine del giorno i punti fondamentali da svolgere sono relativi sia alla documentazione, ovvero rifinire i casi d'uso e i requisiti e ricercare le metriche di qualità, sia alla realizzazione con
Metterei la p maiuscola in PoC

2024-12-24 17:36 UTC, davim02 commented on rtb/verbali/interni/VI_2024-12-23_ver1.0.0.typ
> +Dopo il proficuo incontro svoltosi la settimana precedente con il professor Cardin, in questo _sprint_ si prevede di sistemare tutti i casi d'uso nel documento di Analisi dei Requisiti e, parallelame
Metterei ...parallelamente, definire nello stesso documento i requisiti del progetto. (Non sono sicuro della r maiuscola in requisiti, forse ha senso se ci riferiamo alla sezione del documento con quel nome ma secondo me anche lasciarla minuscola va bene)

2024-12-24 17:36 UTC, davim02 commented on rtb/verbali/interni/VI_2024-12-23_ver1.0.0.typ
> +Continuando il lavoro iniziato nello scorso _sprint_, il gruppo vuole focalizzarsi sulle metriche con cui misurare i progressi del progetto. Per questo sarà importante studiare le metriche di qualità
Io metterei ...metriche con cui monitorare/misurare la qualità del progetto/dei processi e i prodotti coinvolti nella realizzazione del progetto.

A inizio dell'ultima frase metterei "In seguito" al posto di "Riguardo"

2024-12-24 17:36 UTC, davim02 commented on rtb/verbali/interni/VI_2024-12-23_ver1.0.0.typ
> +Lato pratico il punto della situazione è che bisogna ultimare la transizione da #rifGlossario("Apache Nifi") alla costruire un servizio _custom_ di _data #rifGlossario("stream processing")_ utilzzand
...da Apache NiFi a un servizio custom di ... costruito utilizzando il framework Spring

Errore di battitura nell'ultima parola, c'è scritto stream senza la e

Se vuoi puoi mettere queste tre cose in un elenco puntato ma va bene anche così visto che c'è la tabella decisioni alla fine

2024-12-24 17:36 UTC, davim02 commented on rtb/verbali/interni/VI_2024-12-23_ver1.0.0.typ
> +Dopo numerose ricerche nessuno strumento in rapposto costo beneficio si è rivelato essere meglio di #rifGlossario("GitHub") per costruire il #rifGlossario("diagramma di Gantt"). Il gruppo perciò ha d
io scriverei "in termini di costo-beneficio"  e lo sposterei alla fine della frase

2024-12-24 17:36 UTC, davim02 commented on rtb/verbali/interni/VI_2024-12-23_ver1.0.0.typ
> +Dal punto di vista pratico invece l'implementazione di _Spring_, il popolamento del _database_ e l'aggiornamento dell'interfaccia.
metterei un verbo dopo invece, tipo "ci si concentrerà su ..."

Spring lo lascierei senza corsivo visto che più che un termine inglese è un nome proprio/marchio registrato

2024-12-24 17:36 UTC, davim02 commented on rtb/verbali/interni/VI_2024-12-23_ver1.0.0.typ
> +  [Creazione del servizio _custom_ di _data processing_ con _Spring_],
Anche qui stessa cosa di sopra per Spring

2024-12-30 10:58 UTC, MilanRiccardo03 commented
> Ultima piccolezza, forse metterei Indice di Gulpease (con il "di" in mezzo), quindi sarebbe da modificare sia nel VI che nel Glossario

Sul web e su wikipedia leggo Indice Gulpease, ho scritto così per quello, se dici cambio.

2024-12-30 13:10 UTC, davim02 approved these changes

2024-12-30 13:11 UTC, davim02 commented
> > Ultima piccolezza, forse metterei Indice di Gulpease (con il "di" in mezzo), quindi sarebbe da modificare sia nel VI che nel Glossario
> 
> Sul web e su wikipedia leggo Indice Gulpease, ho scritto così per quello, se dici cambio.

No allora va bene come hai scritto

2024-12-30 15:44 UTC, DavidePicc commented
Se non sbaglio per questo verbale dovrei fare temporaneamente io il responsabile, quindi è da cambiare "Responsabile" sulla prima pagina

2024-12-30 15:46 UTC, DavidePicc commented
Noto che la parola database non è stata segnata come riferimento al glossario, infatti il test lo segnala
"Database in rtb\verbali\interni\VI_2024-12-23_ver1.0.0.typ mancante"

2024-12-30 15:50 UTC, DavidePicc commented
Nella riga 38 metterei 
> ... In seguito a un primo studio delle metriche svolto nel precedente _sprint_, si è reso necessario codificare uno _script_ che ~calcola~ calcoli l'#rifGlossario("indice Gulpease").

2024-12-30 15:51 UTC, DavidePicc commented
Per il resto va bene, appena sistemate faccio il merge

2025-01-03 11:43 UTC, merged