redazione pianificazione sprint 4
SWEatUNIPD/docs pull request #95
Opened 2024-12-24 14:33 UTC by MilanRiccardo03

closes #89

2024-12-25 11:15 UTC, DavidePicc requested changes
Mi sembra ben fatto, con qualche piccolissima correzione da apportare

2024-12-25 11:15 UTC, DavidePicc commented on rtb/piano_di_progetto_ver0.6.0.typ
> +- Codifica dello _script_ per il calcolo automatico dell'_#rifGlossario("indice Gulpease")_.
Non vedo la spiegazione del termine nel glossario

2024-12-25 11:15 UTC, DavidePicc commented on rtb/piano_di_progetto_ver0.6.0.typ
> +  - Metriche di qualità del prodotto
Manca il punto finale

2024-12-25 11:15 UTC, DavidePicc commented on rtb/piano_di_progetto_ver0.6.0.typ
> +- Redazione completa del Piano di Qualifica con le metriche individuate nel punto sopra.
Forse meglio "precedente" rispetto a "sopra"

2024-12-25 11:15 UTC, DavidePicc commented on rtb/piano_di_progetto_ver0.6.0.typ
> +  - Rifinire e completare i casi d'uso
Il punto manca anche qui

2024-12-26 14:29 UTC, davim02 requested changes

2024-12-26 14:29 UTC, davim02 commented on rtb/piano_di_progetto_ver0.6.0.typ
> +- Codifica dello _script_ per il calcolo automatico dell'_#rifGlossario("indice Gulpease")_.
C'è, è che l'ha aggiunto nella branch per la stesura del Verbale Interno quindi qui non si vede

2024-12-26 14:29 UTC, davim02 commented on rtb/piano_di_progetto_ver0.6.0.typ
> +  - Individuare e redarre in maniera completa i Requisiti.
redigere (*menacing look from Tullio*)

Anche qui non so se metterei l'iniziale di requisiti in maiuscolo ma se ti riferisci alla sezione del documento allora può andar bene

2024-12-26 14:29 UTC, davim02 commented on rtb/piano_di_progetto_ver0.6.0.typ
> +- Creazione del nuovo _#rifGlossario("stream processor") custom_ sfruttando #rifGlossario("Spring"), con il _database_ popolato e l'integrazione con _#rifGlossario("LangChain")_.
Secondo le NdP LangChain non va in corsivo visto che, più che un termine inglese, è il nome proprio di un software/prodotto

2024-12-26 14:29 UTC, davim02 commented on rtb/piano_di_progetto_ver0.6.0.typ
> +- Aggiornamento della _dashboard_ in Grafana per adattarsi alla nuova infrastruttura con _Spring_.
Stessa cosa di sopra per Spring

2024-12-26 14:34 UTC, davim02 commented on rtb/piano_di_progetto_ver0.6.0.typ
> +- Codifica dello _script_ per il calcolo automatico dell'_#rifGlossario("indice Gulpease")_.
C'è, è che l'ha aggiunta nella branch per la stesura del Verbale Interno quindi qui non si vede

2024-12-30 13:05 UTC, davim02 approved these changes
Tutto ok per il resto, ti metto gia approvato

2024-12-30 13:05 UTC, davim02 commented on rtb/piano_di_progetto_ver0.6.0.typ
>  - Codifica dello _script_ per il calcolo automatico dell'_#rifGlossario("indice Gulpease")_.
Toglierei il corsivo da indice di Gulpease

2024-12-30 15:37 UTC, DavidePicc approved these changes

2025-01-03 11:48 UTC, merged