Sistemazione vecchi UC e aggiunta di nuovi
SWEatUNIPD/docs pull request #96
Opened 2024-12-27 13:53 UTC by ErPreco

2024-12-31 10:18 UTC, DavidePicc requested changes

2024-12-31 10:18 UTC, DavidePicc commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +  + Visualizzazione marker sulla mappa per i punti di interesse (#link(<uc11>)[UC11]).
Marker in rtb\analisi_dei_requisiti_ver0.4.0.typ mancante

2024-12-31 10:18 UTC, DavidePicc commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +  + L'amministratore non autenticato accedere alla pagina di _login_ del sistema.
Piccolo errore sul verbo

2024-12-31 10:18 UTC, DavidePicc commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +  + L'amministratore riceve un messaggio di errore il quale segnala che le credenziali di inserite sono invalide.
>  L'amministratore riceve un messaggio di errore il quale segnala che le credenziali ~di~ inserite sono invalide.

Poi più che "invalide" metterei "non valide"

2024-12-31 10:18 UTC, DavidePicc commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +=== UC9 - Visualizzazione della mappa geografica sulla dashboard
C'è già lo UC9

2024-12-31 10:18 UTC, DavidePicc commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +=== UC9 - Visualizzazione della mappa geografica sulla dashboard
Ok, vedo che ci sono più doppioni, soprattutto alla fine. Non li segnalerò più

2024-12-31 10:18 UTC, DavidePicc commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +  + VISUALIZZAZIONE ANNUNCIO E RELATIVE INFORMAZIONI
Ora mi sembra ci sia lo use case relativo

2024-12-31 10:20 UTC, DavidePicc commented
Poi noto che in 3.3.21, all'ultima riga, c'è scritto 
> 3. La notifica viene chiusa fatta scomparire dalla dashboard.

Non mi sembra corretta
(Questi commenti non posso scriverli come quelli precedenti in quanto non sono modifiche di questa pr)

2024-12-31 10:25 UTC, DavidePicc commented
Nello UC19 (3.3.27) mi sembra ripetitivo scrivere 2 volte
> • Nome del punto di interesse collegato.
• E-mail dell’utente destinatario.
• Data e ora di emissione.
• Un flag che indica se il noleggio al quale è stato inviato l’annuncio è ancora attivo

Infatti è scritto:
>3.3.27 UC19 - Visualizzazione singolo annuncio nello storico
• Attore principale: Amministratore.
• Precondizioni: il sistema tiene traccia delle informazioni principali degli annunci generati per i
clienti dell’amministratore. Questo è autenticato ed è acceduto alla sezione dedicata agli annunci.
• Postcondizioni: il sistema espone le informazioni principali relative al singolo annuncio:
• Nome del punto di interesse collegato.
• E-mail dell’utente destinatario.
• Data e ora di emissione.
• Un flag che indica se il noleggio al quale è stato inviato l’annuncio è ancora attivo.
• Trigger: l’amministratore desidera visualizzare le informazioni principali di un annuncio.
• Scenario principale:
1.L’amministratore visualizza le seguenti informazioni relative all’annuncio:
• Nome del punto di interesse collegato.
• E-mail dell’utente destinatario.
• Data e ora di erogazione.
• Flag che indica se il noleggio al quale è stato inviato l’annuncio è ancora attivo

2024-12-31 10:26 UTC, DavidePicc commented
3.3.29 UC21
> • Trigger: l’amministratore desidera visualizzare l’e-mail dell’**untente** destinatario dell’annuncio.

2024-12-31 10:32 UTC, DavidePicc commented
In 3.3.26 UC28, la parte sottolineata non mi sembra corretta
> • Postcondizioni: il sistema espone gli annunci generati fino a quel momento ordinati dal più recente
<ins>in formato a lista</ins>

2024-12-31 10:39 UTC, DavidePicc commented
In 3.3.39 non mi fa impazzire "è acceduto" (usato più volte nel documento, ma mi è saltato più all'occhio qui)
> L’amministratore <ins>è acceduto</ins> alla sezione dedicata

2024-12-31 10:39 UTC, ErPreco commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +  + VISUALIZZAZIONE ANNUNCIO E RELATIVE INFORMAZIONI
sì infatti devo aggiungerlo, volevo solo capire bene se è corretto e come organizzarli visto che servirebbero i link ma rinumerando gli uc verrebbero tutti sballati di nuovo

2024-12-31 10:47 UTC, ErPreco commented
> Nello UC19 (3.3.27) mi sembra ripetitivo scrivere 2 volte
> 
> > • Nome del punto di interesse collegato.
> > • E-mail dell’utente destinatario.
> > • Data e ora di emissione.
> > • Un flag che indica se il noleggio al quale è stato inviato l’annuncio è ancora attivo
> 
> Infatti è scritto:
> 
> > 3.3.27 UC19 - Visualizzazione singolo annuncio nello storico
> > • Attore principale: Amministratore.
> > • Precondizioni: il sistema tiene traccia delle informazioni principali degli annunci generati per i
> > clienti dell’amministratore. Questo è autenticato ed è acceduto alla sezione dedicata agli annunci.
> > • Postcondizioni: il sistema espone le informazioni principali relative al singolo annuncio:
> > • Nome del punto di interesse collegato.
> > • E-mail dell’utente destinatario.
> > • Data e ora di emissione.
> > • Un flag che indica se il noleggio al quale è stato inviato l’annuncio è ancora attivo.
> > • Trigger: l’amministratore desidera visualizzare le informazioni principali di un annuncio.
> > • Scenario principale:
> > 1.L’amministratore visualizza le seguenti informazioni relative all’annuncio:
> > • Nome del punto di interesse collegato.
> > • E-mail dell’utente destinatario.
> > • Data e ora di erogazione.
> > • Flag che indica se il noleggio al quale è stato inviato l’annuncio è ancora attivo
> 
> Idem in 3.3.24 ed in 3.3.44

Effettivamente è ridondante, solo volevo essere esplicito.

2024-12-31 10:48 UTC, ErPreco commented
> 3.3.29 UC21
> 
> > • Trigger: l’amministratore desidera visualizzare l’e-mail dell’**untente** destinatario dell’annuncio.

risolto

2024-12-31 10:52 UTC, ErPreco commented
> In 3.3.26 UC28, la parte sottolineata non mi sembra corretta
> 
> > • Postcondizioni: il sistema espone gli annunci generati fino a quel momento ordinati dal più recente
> > in formato a lista
> > • Trigger: l’amministratore vuole prendere visione degli annunci generati fino a quel momento in
> > formato a lista.
> > • Scenario principale:
> 
> 1. L’amministratore accede alla dashboard principale.
> 2. L’amministratore accede alla sezione apposita degli annunci.
> 3. L’amministratore selezione l’opzione per visualizzare gli annunci in formato a lista
> 
> Idem in 3.3.27 UC29 con "in formato a griglia"

risolto

2024-12-31 10:54 UTC, ErPreco commented
> In 3.3.39 non mi fa impazzire "è acceduto" (usato più volte nel documento, ma mi è saltato più all'occhio qui)
> 
> > L’amministratore è acceduto alla sezione dedicata

è la coniugazione al passato di accedere, posso metterla al presente ma è quello (scrivendo tanti uc può essere non abbia mantenuto una coerenza verbale)

2025-01-02 09:17 UTC, DavidePicc commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +  + Visualizzazione marker sulla mappa per i punti di interesse (#link(<uc11>)[UC11]).
Qui intendevo che Marker è un termine del glossario e non è segnato. Avevo incollato nella review il  messaggio del test, forse non ero stato chiaro.

2025-01-02 09:18 UTC, DavidePicc commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +  + Visualizzazione marker sulla mappa per i punti di interesse (#link(<uc11>)[UC11]).
Tra l'altro a riga 311 in "3.3.8 UC11 - Visualizzazione percorso del mezzo in noleggio sulla mappa" non è  in corsivo

2025-01-02 09:23 UTC, DavidePicc commented
> Poi noto che in 3.3.21, all'ultima riga, c'è scritto
> 
> > 3. La notifica viene chiusa fatta scomparire dalla dashboard.
> 
> Non mi sembra corretta (Questi commenti non posso scriverli come quelli precedenti in quanto non sono modifiche di questa pr)

Questo non è stato sistemato :(

2025-01-02 09:25 UTC, DavidePicc commented
> Nello UC19 (3.3.27) mi sembra ripetitivo scrivere 2 volte
> 
> > • Nome del punto di interesse collegato.
> > • E-mail dell’utente destinatario.
> > • Data e ora di emissione.
> > • Un flag che indica se il noleggio al quale è stato inviato l’annuncio è ancora attivo
> 
> Infatti è scritto:
> 
> > 3.3.27 UC19 - Visualizzazione singolo annuncio nello storico
> > • Attore principale: Amministratore.
> > • Precondizioni: il sistema tiene traccia delle informazioni principali degli annunci generati per i
> > clienti dell’amministratore. Questo è autenticato ed è acceduto alla sezione dedicata agli annunci.
> > • Postcondizioni: il sistema espone le informazioni principali relative al singolo annuncio:
> > • Nome del punto di interesse collegato.
> > • E-mail dell’utente destinatario.
> > • Data e ora di emissione.
> > • Un flag che indica se il noleggio al quale è stato inviato l’annuncio è ancora attivo.
> > • Trigger: l’amministratore desidera visualizzare le informazioni principali di un annuncio.
> > • Scenario principale:
> > 1.L’amministratore visualizza le seguenti informazioni relative all’annuncio:
> > • Nome del punto di interesse collegato.
> > • E-mail dell’utente destinatario.
> > • Data e ora di erogazione.
> > • Flag che indica se il noleggio al quale è stato inviato l’annuncio è ancora attivo
> 
> Idem in 3.3.24 ed in 3.3.44

Anche questo non è stato sistemato

2025-01-02 09:29 UTC, DavidePicc commented
> > In 3.3.39 non mi fa impazzire "è acceduto" (usato più volte nel documento, ma mi è saltato più all'occhio qui)
> > > L’amministratore è acceduto alla sezione dedicata
> 
> è la coniugazione al passato di accedere, posso metterla al presente ma è quello (scrivendo tanti uc può essere non abbia mantenuto una coerenza verbale)

Grammaticalmente va bene. Personalmente avrei preferito qualcosa tipo "ha eseguito l'accesso".

2025-01-02 09:29 UTC, DavidePicc requested changes

2025-01-02 09:29 UTC, DavidePicc commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +  + Visualizzazione marker sul tracciato dei mezzi con noleggio attivo in corrispondenza del dato GPS (#link(<uc9>)[UC9]).
marker non è in corsivo

2025-01-02 09:29 UTC, DavidePicc commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +  + L'amministratore riceve un messaggio di errore il quale segnala che le credenziali di inserite sono invalide.
Qui avevo anche segnato "~di~" per dire di toglierlo

2025-01-02 09:30 UTC, DavidePicc commented
Ci sono solo cose piccole da cambiare, entro oggi si può chiudere questa pr secondo me

2025-01-03 10:06 UTC, DavidePicc approved these changes
Mi sembra vada bene

2025-01-03 17:37 UTC, Perruzz commented
@ErPreco ho toccato i titoli dei tuoi 4 UC che ti dicevo e ritoccato il contenuto dei 3 di poi, email utente e data/ora, fammi sapere se vanno bene

2025-01-07 09:06 UTC, DavidePicc commented
Siccome vedo che continuate a pushsare, quando serve la revisione finale richiedete di nuovo la nostra revisione

2025-01-07 15:03 UTC, davim02 requested changes
Forse non è cauto lasciare l' "Utente" a riga 114 visto che non sappiamo se faremo anche quella parte essendo opzionale, poi non so ditemi voi

Altra cosa, in diversi uc è scritto "Questo visualizza la sezione dedicata agli annunci" nelle precondizioni, non so mi suona strano dire che il sistema visualizza, io forse metterei mostra

2025-01-07 15:03 UTC, davim02 commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +- *Trigger*: l'amministratore intende accede alla _dashboard_ personale.
*accedere

2025-01-07 15:03 UTC, davim02 commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +  + L'amministratore visualizza un _marker_ in corrispondenza delle posizioni nelle quali la LLM non ha generato un annuncio..
*il LLM (perchè è model)

2025-01-07 15:03 UTC, davim02 commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +- *Postcondizioni*: il sistema mostra una notifica sulla _dashboard_ contenente le informazioni principlai riguardo alla mancata generazione di un annuncio.
*principali

2025-01-07 15:38 UTC, ErPreco commented
> Forse non è cauto lasciare l' "Utente" a riga 114 visto che non sappiamo se faremo anche quella parte essendo opzionale, poi non so ditemi voi

penso tu intenda a riga 115, concordo anche perché la web app sarebbe parecchia roba da aggiungere, per ora la tolgo

> Altra cosa, in diversi uc è scritto "Questo visualizza la sezione dedicata agli annunci" nelle precondizioni, non so mi suona strano dire che il sistema visualizza, io forse metterei mostra

"questo" si riferisce all'ultimo soggetto quindi amministratore, era per non ripetere "... dell'amministratore. L'amministratore ..."

2025-01-07 15:49 UTC, ErPreco commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +  + L'amministratore visualizza un _marker_ in corrispondenza delle posizioni nelle quali la LLM non ha generato un annuncio..
concordo però mi pare che in altri documenti sia lasciato al femminile, non cambia molto ma basta ci sia coerenza almeno all'interno dello stesso (ci sono molte occorrenze di LLM tutte al femminile)

2025-01-07 20:23 UTC, davim02 commented on rtb/analisi_dei_requisiti_ver0.4.0.typ
> +  + L'amministratore visualizza un _marker_ in corrispondenza delle posizioni nelle quali la LLM non ha generato un annuncio..
Ok, allora rimette pure il la

2025-01-07 20:24 UTC, davim02 commented
> > Altra cosa, in diversi uc è scritto "Questo visualizza la sezione dedicata agli annunci" nelle precondizioni, non so mi suona strano dire che il sistema visualizza, io forse metterei mostra
> 
> "questo" si riferisce all'ultimo soggetto quindi amministratore, era per non ripetere "... dell'amministratore. L'amministratore ..."

capito, avevo frainteso io

2025-01-07 20:24 UTC, davim02 approved these changes

2025-01-07 20:33 UTC, davim02 commented
Vi ho gia messo approvato ma manca:
- togliere o commentare la parte sull'utente a linea 115
- rimettere "la" al posto di "il"

2025-01-10 12:54 UTC, merged