Stesura del VE_2024-12-23
SWEatUNIPD/docs pull request #97
Opened 2024-12-30 09:00 UTC by MarinDavide

closes #84

2024-12-30 22:54 UTC, davim02 requested changes

2024-12-30 22:54 UTC, davim02 commented on rtb/verbali/esterni/VE_2024-12-23_ver1.0.0.typ
> +    "Davide Picello",
Sbagliato Davide, è Davide Martinelli

2024-12-30 22:54 UTC, davim02 commented on rtb/verbali/esterni/VE_2024-12-23_ver1.0.0.typ
> +    "Davide Marin", "Davide Picello",
Quindi anche qui va cambiato

2024-12-30 22:54 UTC, davim02 commented on rtb/verbali/esterni/VE_2024-12-23_ver1.0.0.typ
> +    "Andrea Perozzo",
Andrea Perozzo non c'era, Picello in teoria si

2024-12-30 22:54 UTC, davim02 commented on rtb/verbali/esterni/VE_2024-12-23_ver1.0.0.typ
> +#infoRiunione(luogo: "Google Meet", data: "23/12/2024", ora: "10:00", durata: "30 minuti", partecipantiEsterni: ("Andrea Dorigo","Fabio Pallaro"),
Tra i partecipanti esterni c'era anche il terzo che di solito non c'è, dovrebbe chiamarsi Daniele Zorzi

2024-12-30 22:54 UTC, davim02 commented on rtb/verbali/esterni/VE_2024-12-23_ver1.0.0.typ
> +Nello specifico si è prima prima parlato dell'incontro avvenuto con il prof. Cardin in data 19/12/2024, e in seguito discusso dell'interfaccia grafica lato amministratore e di alcuni possibili casi d
prima è ripetuto 2 volte

Io metterei "Nello specifico, prima si è parlato..." e poi la virgola dopo 2024 forse si può anche togliere

Non son sicuro ma l'ultima parola mi verrebbe da scrivere tra virgolette e/o con la a maiuscola

2024-12-30 22:54 UTC, davim02 commented on rtb/verbali/esterni/VE_2024-12-23_ver1.0.0.typ
> +L'incontro ha portato a termine il terzo _#rifGlossario("sprint")_, durante l'incontro sono state discusse le possibili implementazioni di alcuni dei requisiti.
Metterei il punto al posto della virgola, creando due frasi

2024-12-30 22:54 UTC, davim02 commented on rtb/verbali/esterni/VE_2024-12-23_ver1.0.0.typ
> +La proposta presentata di creare un'interfaccia suddivisa in due schermate principali è stata accettata. La prima schermata conterrà la mappa geografica con al suo interno punti evidenziati che rappr
Scriverei "la mappa geografica, al cui interno saranno evidenziati i punti che rappresentano la posizione degli utenti e dei punti di interesse, mentre la seconda..."

2024-12-30 22:54 UTC, davim02 commented on rtb/verbali/esterni/VE_2024-12-23_ver1.0.0.typ
> +Nello specifico, appariranno dei _popup_ a lato dello schermo ogni qualvolta verrà generata una pubblicità; inoltre, sarà possibile visualizzare le pubblicità generate per un determinato utente effet
"... sarà possibile visualizzare la pubblicità/l'annuncio generata/o per un determinato utente in un determinato punto effettuando un "_~~hoover~~ hover_" (con il puntatore del _mouse_) sul punto stesso..."

Nota: le parentesi indicano che quella parte è facoltativo metterla

2024-12-30 22:54 UTC, davim02 commented on rtb/verbali/esterni/VE_2024-12-23_ver1.0.0.typ
> +Per il momento,è stato confermato che lo storico annunci deve essere filtrabile per utente e per punto di interesse, ma è possibile implementarne degli altri se ritenuti utili in corso di sviluppo. I
Toglierei la prima virgola

Specificherei il ne: "è possibile implementare altri filtri se..."

Per quanto riguarda la seconda parte se non ricordo male avevano detto di poter vedere gli annunci generati per un utente cliccando su una posizione di quell'utente sulla mappa (uguale a ciò che succede con i punti d'interesse). Io scriverei una cosa del tipo:
"Inoltre, una possibile implementazione dello storico annunci, oltre alla schermata dedicata, potrebbe essere la possibilità di visualizzare, contestualmente ad un _click_ del _mouse_ su un punto di interesse o una posizione di un utente all'interno della mappa, la lista degli annunci generati per quel punto di interesse o utente specifico."

2024-12-30 22:54 UTC, davim02 commented on rtb/verbali/esterni/VE_2024-12-23_ver1.0.0.typ
> +Il prossimo incontro con l'azienda sarà il mercoledì 8 gennaio e come obiettivo ci siamo posti di riuscire a mandare le richieste di annunci personalizzati al LLM.
sarà mercoledì (senza il)

2024-12-30 22:54 UTC, davim02 commented on rtb/verbali/esterni/VE_2024-12-23_ver1.0.0.typ
> +In definitiva, andranno inseriti controlli ed errori nei casi d'uso, ma non è necessario che ne implementiamo di nostri in quanto Grafana gestisce autonomamente tutti gli aspetti della connessione al
Giusto quello che hai scritto nel paragrafo però vale anche per il login, quindi sistemerei frasi e titolo in modo da includerlo

2024-12-30 22:54 UTC, davim02 commented on rtb/verbali/esterni/VE_2024-12-23_ver1.0.0.typ
> +Alla fine della riunione, ci siamo prefissati, assieme ai proponenti, di riuscire a mandare le richieste di annunci personalizzati al #rifGlossario("LLM") entro il termine del prossimo _sprint_.
Potrebbe aver senso sostituire mandare con gestire?

2024-12-31 13:22 UTC, davim02 approved these changes
Per il resto mi sembra tutto ok. Metto già approvato

2024-12-31 13:22 UTC, davim02 commented on rtb/verbali/esterni/VE_2024-12-23_ver1.0.0.typ
> +Il prossimo incontro con l'azienda sarà mercoledì 8 gennaio e come obiettivo ci siamo posti di riuscire a mandare le richieste di annunci personalizzati al LLM.
metterei "...riuscire a gestire le richieste..." o ancora meglio "...riuscire a implementare la gestione delle richieste..."

2025-01-04 14:53 UTC, MarinDavide commented
scrivo anche qui, ho cambiato la parte di obiettivi @MilanRiccardo03 (taggo anche @davim02 se vuole dare una controllata)

2025-01-05 14:15 UTC, davim02 approved these changes
Per me tutto ok

2025-01-05 14:32 UTC, merged